"""
连一连游戏题库（以阅读为主，全文字内容）
难度分级：
  L1 — 汉字-汉字配对（相同字/词），4 对
  L2 — 词语-词语配对（近义词），4-5 对
  L3 — 词语-词语配对（反义词/关联词），5-6 对
"""
from typing import List, Dict, Any

CONNECT_QUESTIONS: Dict[str, List[Dict[str, Any]]] = {
    "L1": [
        # 相同汉字连线（认字练习）—— 共30题，每次随机抽10题
        {
            "id": "connect_L1_001",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "山"}, "right": {"type": "text", "content": "山"}},
                {"left": {"type": "text", "content": "水"}, "right": {"type": "text", "content": "水"}},
                {"left": {"type": "text", "content": "日"}, "right": {"type": "text", "content": "日"}},
                {"left": {"type": "text", "content": "月"}, "right": {"type": "text", "content": "月"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_002",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "火"}, "right": {"type": "text", "content": "火"}},
                {"left": {"type": "text", "content": "木"}, "right": {"type": "text", "content": "木"}},
                {"left": {"type": "text", "content": "土"}, "right": {"type": "text", "content": "土"}},
                {"left": {"type": "text", "content": "金"}, "right": {"type": "text", "content": "金"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_003",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "风"}, "right": {"type": "text", "content": "风"}},
                {"left": {"type": "text", "content": "云"}, "right": {"type": "text", "content": "云"}},
                {"left": {"type": "text", "content": "花"}, "right": {"type": "text", "content": "花"}},
                {"left": {"type": "text", "content": "草"}, "right": {"type": "text", "content": "草"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_004",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "鸟"}, "right": {"type": "text", "content": "鸟"}},
                {"left": {"type": "text", "content": "鱼"}, "right": {"type": "text", "content": "鱼"}},
                {"left": {"type": "text", "content": "猫"}, "right": {"type": "text", "content": "猫"}},
                {"left": {"type": "text", "content": "狗"}, "right": {"type": "text", "content": "狗"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_005",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "牛"}, "right": {"type": "text", "content": "牛"}},
                {"left": {"type": "text", "content": "羊"}, "right": {"type": "text", "content": "羊"}},
                {"left": {"type": "text", "content": "马"}, "right": {"type": "text", "content": "马"}},
                {"left": {"type": "text", "content": "虎"}, "right": {"type": "text", "content": "虎"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_006",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "大"}, "right": {"type": "text", "content": "大"}},
                {"left": {"type": "text", "content": "小"}, "right": {"type": "text", "content": "小"}},
                {"left": {"type": "text", "content": "上"}, "right": {"type": "text", "content": "上"}},
                {"left": {"type": "text", "content": "下"}, "right": {"type": "text", "content": "下"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_007",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "左"}, "right": {"type": "text", "content": "左"}},
                {"left": {"type": "text", "content": "右"}, "right": {"type": "text", "content": "右"}},
                {"left": {"type": "text", "content": "前"}, "right": {"type": "text", "content": "前"}},
                {"left": {"type": "text", "content": "后"}, "right": {"type": "text", "content": "后"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_008",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "红"}, "right": {"type": "text", "content": "红"}},
                {"left": {"type": "text", "content": "蓝"}, "right": {"type": "text", "content": "蓝"}},
                {"left": {"type": "text", "content": "绿"}, "right": {"type": "text", "content": "绿"}},
                {"left": {"type": "text", "content": "黄"}, "right": {"type": "text", "content": "黄"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_009",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "一"}, "right": {"type": "text", "content": "一"}},
                {"left": {"type": "text", "content": "二"}, "right": {"type": "text", "content": "二"}},
                {"left": {"type": "text", "content": "三"}, "right": {"type": "text", "content": "三"}},
                {"left": {"type": "text", "content": "四"}, "right": {"type": "text", "content": "四"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_010",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "五"}, "right": {"type": "text", "content": "五"}},
                {"left": {"type": "text", "content": "六"}, "right": {"type": "text", "content": "六"}},
                {"left": {"type": "text", "content": "七"}, "right": {"type": "text", "content": "七"}},
                {"left": {"type": "text", "content": "八"}, "right": {"type": "text", "content": "八"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_011",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "九"}, "right": {"type": "text", "content": "九"}},
                {"left": {"type": "text", "content": "十"}, "right": {"type": "text", "content": "十"}},
                {"left": {"type": "text", "content": "百"}, "right": {"type": "text", "content": "百"}},
                {"left": {"type": "text", "content": "千"}, "right": {"type": "text", "content": "千"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_012",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "人"}, "right": {"type": "text", "content": "人"}},
                {"left": {"type": "text", "content": "口"}, "right": {"type": "text", "content": "口"}},
                {"left": {"type": "text", "content": "手"}, "right": {"type": "text", "content": "手"}},
                {"left": {"type": "text", "content": "足"}, "right": {"type": "text", "content": "足"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_013",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "目"}, "right": {"type": "text", "content": "目"}},
                {"left": {"type": "text", "content": "耳"}, "right": {"type": "text", "content": "耳"}},
                {"left": {"type": "text", "content": "鼻"}, "right": {"type": "text", "content": "鼻"}},
                {"left": {"type": "text", "content": "心"}, "right": {"type": "text", "content": "心"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_014",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "天"}, "right": {"type": "text", "content": "天"}},
                {"left": {"type": "text", "content": "地"}, "right": {"type": "text", "content": "地"}},
                {"left": {"type": "text", "content": "家"}, "right": {"type": "text", "content": "家"}},
                {"left": {"type": "text", "content": "国"}, "right": {"type": "text", "content": "国"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_015",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "书"}, "right": {"type": "text", "content": "书"}},
                {"left": {"type": "text", "content": "笔"}, "right": {"type": "text", "content": "笔"}},
                {"left": {"type": "text", "content": "纸"}, "right": {"type": "text", "content": "纸"}},
                {"left": {"type": "text", "content": "字"}, "right": {"type": "text", "content": "字"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_016",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "苹"}, "right": {"type": "text", "content": "苹"}},
                {"left": {"type": "text", "content": "果"}, "right": {"type": "text", "content": "果"}},
                {"left": {"type": "text", "content": "梨"}, "right": {"type": "text", "content": "梨"}},
                {"left": {"type": "text", "content": "桃"}, "right": {"type": "text", "content": "桃"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_017",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "春"}, "right": {"type": "text", "content": "春"}},
                {"left": {"type": "text", "content": "夏"}, "right": {"type": "text", "content": "夏"}},
                {"left": {"type": "text", "content": "秋"}, "right": {"type": "text", "content": "秋"}},
                {"left": {"type": "text", "content": "冬"}, "right": {"type": "text", "content": "冬"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_018",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "东"}, "right": {"type": "text", "content": "东"}},
                {"left": {"type": "text", "content": "西"}, "right": {"type": "text", "content": "西"}},
                {"left": {"type": "text", "content": "南"}, "right": {"type": "text", "content": "南"}},
                {"left": {"type": "text", "content": "北"}, "right": {"type": "text", "content": "北"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_019",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "爸"}, "right": {"type": "text", "content": "爸"}},
                {"left": {"type": "text", "content": "妈"}, "right": {"type": "text", "content": "妈"}},
                {"left": {"type": "text", "content": "哥"}, "right": {"type": "text", "content": "哥"}},
                {"left": {"type": "text", "content": "姐"}, "right": {"type": "text", "content": "姐"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_020",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "弟"}, "right": {"type": "text", "content": "弟"}},
                {"left": {"type": "text", "content": "妹"}, "right": {"type": "text", "content": "妹"}},
                {"left": {"type": "text", "content": "爷"}, "right": {"type": "text", "content": "爷"}},
                {"left": {"type": "text", "content": "奶"}, "right": {"type": "text", "content": "奶"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_021",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "吃"}, "right": {"type": "text", "content": "吃"}},
                {"left": {"type": "text", "content": "喝"}, "right": {"type": "text", "content": "喝"}},
                {"left": {"type": "text", "content": "跑"}, "right": {"type": "text", "content": "跑"}},
                {"left": {"type": "text", "content": "跳"}, "right": {"type": "text", "content": "跳"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_022",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "看"}, "right": {"type": "text", "content": "看"}},
                {"left": {"type": "text", "content": "听"}, "right": {"type": "text", "content": "听"}},
                {"left": {"type": "text", "content": "说"}, "right": {"type": "text", "content": "说"}},
                {"left": {"type": "text", "content": "写"}, "right": {"type": "text", "content": "写"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_023",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "好"}, "right": {"type": "text", "content": "好"}},
                {"left": {"type": "text", "content": "坏"}, "right": {"type": "text", "content": "坏"}},
                {"left": {"type": "text", "content": "多"}, "right": {"type": "text", "content": "多"}},
                {"left": {"type": "text", "content": "少"}, "right": {"type": "text", "content": "少"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_024",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "长"}, "right": {"type": "text", "content": "长"}},
                {"left": {"type": "text", "content": "短"}, "right": {"type": "text", "content": "短"}},
                {"left": {"type": "text", "content": "高"}, "right": {"type": "text", "content": "高"}},
                {"left": {"type": "text", "content": "低"}, "right": {"type": "text", "content": "低"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_025",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "快"}, "right": {"type": "text", "content": "快"}},
                {"left": {"type": "text", "content": "慢"}, "right": {"type": "text", "content": "慢"}},
                {"left": {"type": "text", "content": "冷"}, "right": {"type": "text", "content": "冷"}},
                {"left": {"type": "text", "content": "热"}, "right": {"type": "text", "content": "热"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_026",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "新"}, "right": {"type": "text", "content": "新"}},
                {"left": {"type": "text", "content": "旧"}, "right": {"type": "text", "content": "旧"}},
                {"left": {"type": "text", "content": "早"}, "right": {"type": "text", "content": "早"}},
                {"left": {"type": "text", "content": "晚"}, "right": {"type": "text", "content": "晚"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_027",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "来"}, "right": {"type": "text", "content": "来"}},
                {"left": {"type": "text", "content": "去"}, "right": {"type": "text", "content": "去"}},
                {"left": {"type": "text", "content": "开"}, "right": {"type": "text", "content": "开"}},
                {"left": {"type": "text", "content": "关"}, "right": {"type": "text", "content": "关"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_028",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "买"}, "right": {"type": "text", "content": "买"}},
                {"left": {"type": "text", "content": "卖"}, "right": {"type": "text", "content": "卖"}},
                {"left": {"type": "text", "content": "问"}, "right": {"type": "text", "content": "问"}},
                {"left": {"type": "text", "content": "答"}, "right": {"type": "text", "content": "答"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_029",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "哭"}, "right": {"type": "text", "content": "哭"}},
                {"left": {"type": "text", "content": "笑"}, "right": {"type": "text", "content": "笑"}},
                {"left": {"type": "text", "content": "爱"}, "right": {"type": "text", "content": "爱"}},
                {"left": {"type": "text", "content": "恨"}, "right": {"type": "text", "content": "恨"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_L1_030",
            "difficulty": "L1",
            "type": "text_text",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "学"}, "right": {"type": "text", "content": "学"}},
                {"left": {"type": "text", "content": "校"}, "right": {"type": "text", "content": "校"}},
                {"left": {"type": "text", "content": "老"}, "right": {"type": "text", "content": "老"}},
                {"left": {"type": "text", "content": "师"}, "right": {"type": "text", "content": "师"}},
            ],
            "time_limit": 60,
        },
    ],
    "L2": [
        # 近义词连线 —— 共30题，每次随机抽10题
        {
            "id": "connect_L2_001",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "高兴"}, "right": {"type": "text", "content": "快乐"}},
                {"left": {"type": "text", "content": "漂亮"}, "right": {"type": "text", "content": "美丽"}},
                {"left": {"type": "text", "content": "害怕"}, "right": {"type": "text", "content": "恐惧"}},
                {"left": {"type": "text", "content": "聪明"}, "right": {"type": "text", "content": "智慧"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_002",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "勇敢"}, "right": {"type": "text", "content": "胆大"}},
                {"left": {"type": "text", "content": "悲伤"}, "right": {"type": "text", "content": "难过"}},
                {"left": {"type": "text", "content": "奔跑"}, "right": {"type": "text", "content": "飞奔"}},
                {"left": {"type": "text", "content": "寻找"}, "right": {"type": "text", "content": "寻觅"}},
                {"left": {"type": "text", "content": "帮助"}, "right": {"type": "text", "content": "援助"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L2_003",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "开心"}, "right": {"type": "text", "content": "愉快"}},
                {"left": {"type": "text", "content": "温柔"}, "right": {"type": "text", "content": "温和"}},
                {"left": {"type": "text", "content": "坚强"}, "right": {"type": "text", "content": "坚韧"}},
                {"left": {"type": "text", "content": "思念"}, "right": {"type": "text", "content": "想念"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_004",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "宽广"}, "right": {"type": "text", "content": "辽阔"}},
                {"left": {"type": "text", "content": "清晰"}, "right": {"type": "text", "content": "清楚"}},
                {"left": {"type": "text", "content": "珍贵"}, "right": {"type": "text", "content": "宝贵"}},
                {"left": {"type": "text", "content": "迅速"}, "right": {"type": "text", "content": "快速"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_005",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "安静"}, "right": {"type": "text", "content": "宁静"}},
                {"left": {"type": "text", "content": "欢喜"}, "right": {"type": "text", "content": "喜悦"}},
                {"left": {"type": "text", "content": "明亮"}, "right": {"type": "text", "content": "光亮"}},
                {"left": {"type": "text", "content": "柔软"}, "right": {"type": "text", "content": "柔和"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_006",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "强壮"}, "right": {"type": "text", "content": "健壮"}},
                {"left": {"type": "text", "content": "仔细"}, "right": {"type": "text", "content": "认真"}},
                {"left": {"type": "text", "content": "喜爱"}, "right": {"type": "text", "content": "热爱"}},
                {"left": {"type": "text", "content": "担心"}, "right": {"type": "text", "content": "忧虑"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_007",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "奇怪"}, "right": {"type": "text", "content": "奇特"}},
                {"left": {"type": "text", "content": "整洁"}, "right": {"type": "text", "content": "干净"}},
                {"left": {"type": "text", "content": "疲惫"}, "right": {"type": "text", "content": "疲倦"}},
                {"left": {"type": "text", "content": "聪慧"}, "right": {"type": "text", "content": "机智"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_008",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "忧愁"}, "right": {"type": "text", "content": "忧郁"}},
                {"left": {"type": "text", "content": "保护"}, "right": {"type": "text", "content": "守护"}},
                {"left": {"type": "text", "content": "美好"}, "right": {"type": "text", "content": "美妙"}},
                {"left": {"type": "text", "content": "快活"}, "right": {"type": "text", "content": "欢乐"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_009",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "勤劳"}, "right": {"type": "text", "content": "勤奋"}},
                {"left": {"type": "text", "content": "聪颖"}, "right": {"type": "text", "content": "聪明"}},
                {"left": {"type": "text", "content": "善意"}, "right": {"type": "text", "content": "好意"}},
                {"left": {"type": "text", "content": "坚持"}, "right": {"type": "text", "content": "坚守"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_010",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "感谢"}, "right": {"type": "text", "content": "感激"}},
                {"left": {"type": "text", "content": "期待"}, "right": {"type": "text", "content": "盼望"}},
                {"left": {"type": "text", "content": "惊讶"}, "right": {"type": "text", "content": "惊奇"}},
                {"left": {"type": "text", "content": "平静"}, "right": {"type": "text", "content": "平和"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_011",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "广阔"}, "right": {"type": "text", "content": "宽阔"}},
                {"left": {"type": "text", "content": "温暖"}, "right": {"type": "text", "content": "暖和"}},
                {"left": {"type": "text", "content": "清凉"}, "right": {"type": "text", "content": "凉爽"}},
                {"left": {"type": "text", "content": "鲜艳"}, "right": {"type": "text", "content": "艳丽"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_012",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "高大"}, "right": {"type": "text", "content": "高耸"}},
                {"left": {"type": "text", "content": "微小"}, "right": {"type": "text", "content": "细小"}},
                {"left": {"type": "text", "content": "宽敞"}, "right": {"type": "text", "content": "宽阔"}},
                {"left": {"type": "text", "content": "狭窄"}, "right": {"type": "text", "content": "狭小"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_013",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "著名"}, "right": {"type": "text", "content": "有名"}},
                {"left": {"type": "text", "content": "普通"}, "right": {"type": "text", "content": "平常"}},
                {"left": {"type": "text", "content": "特别"}, "right": {"type": "text", "content": "特殊"}},
                {"left": {"type": "text", "content": "重要"}, "right": {"type": "text", "content": "重大"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_014",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "完整"}, "right": {"type": "text", "content": "完全"}},
                {"left": {"type": "text", "content": "正确"}, "right": {"type": "text", "content": "准确"}},
                {"left": {"type": "text", "content": "错误"}, "right": {"type": "text", "content": "错乱"}},
                {"left": {"type": "text", "content": "困难"}, "right": {"type": "text", "content": "艰难"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_015",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "容易"}, "right": {"type": "text", "content": "简单"}},
                {"left": {"type": "text", "content": "复杂"}, "right": {"type": "text", "content": "繁杂"}},
                {"left": {"type": "text", "content": "简洁"}, "right": {"type": "text", "content": "简单"}},
                {"left": {"type": "text", "content": "丰富"}, "right": {"type": "text", "content": "充足"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_016",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "努力"}, "right": {"type": "text", "content": "用功"}},
                {"left": {"type": "text", "content": "认真"}, "right": {"type": "text", "content": "专心"}},
                {"left": {"type": "text", "content": "刻苦"}, "right": {"type": "text", "content": "勤苦"}},
                {"left": {"type": "text", "content": "进步"}, "right": {"type": "text", "content": "提高"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_017",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "友好"}, "right": {"type": "text", "content": "友善"}},
                {"left": {"type": "text", "content": "热情"}, "right": {"type": "text", "content": "热心"}},
                {"left": {"type": "text", "content": "冷漠"}, "right": {"type": "text", "content": "冷淡"}},
                {"left": {"type": "text", "content": "亲切"}, "right": {"type": "text", "content": "亲近"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_018",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "快乐"}, "right": {"type": "text", "content": "幸福"}},
                {"left": {"type": "text", "content": "痛苦"}, "right": {"type": "text", "content": "苦恼"}},
                {"left": {"type": "text", "content": "满足"}, "right": {"type": "text", "content": "满意"}},
                {"left": {"type": "text", "content": "失望"}, "right": {"type": "text", "content": "沮丧"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_019",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "希望"}, "right": {"type": "text", "content": "愿望"}},
                {"left": {"type": "text", "content": "梦想"}, "right": {"type": "text", "content": "理想"}},
                {"left": {"type": "text", "content": "目标"}, "right": {"type": "text", "content": "志向"}},
                {"left": {"type": "text", "content": "信心"}, "right": {"type": "text", "content": "信念"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_020",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "勇气"}, "right": {"type": "text", "content": "胆量"}},
                {"left": {"type": "text", "content": "力量"}, "right": {"type": "text", "content": "力气"}},
                {"left": {"type": "text", "content": "智慧"}, "right": {"type": "text", "content": "才智"}},
                {"left": {"type": "text", "content": "品德"}, "right": {"type": "text", "content": "品质"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_021",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "创造"}, "right": {"type": "text", "content": "创作"}},
                {"left": {"type": "text", "content": "发现"}, "right": {"type": "text", "content": "发觉"}},
                {"left": {"type": "text", "content": "探索"}, "right": {"type": "text", "content": "探究"}},
                {"left": {"type": "text", "content": "研究"}, "right": {"type": "text", "content": "探讨"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_022",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "保护"}, "right": {"type": "text", "content": "爱护"}},
                {"left": {"type": "text", "content": "珍惜"}, "right": {"type": "text", "content": "爱惜"}},
                {"left": {"type": "text", "content": "节约"}, "right": {"type": "text", "content": "节省"}},
                {"left": {"type": "text", "content": "浪费"}, "right": {"type": "text", "content": "挥霍"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_023",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "整齐"}, "right": {"type": "text", "content": "有序"}},
                {"left": {"type": "text", "content": "混乱"}, "right": {"type": "text", "content": "杂乱"}},
                {"left": {"type": "text", "content": "有趣"}, "right": {"type": "text", "content": "有意思"}},
                {"left": {"type": "text", "content": "无聊"}, "right": {"type": "text", "content": "枯燥"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_024",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "安全"}, "right": {"type": "text", "content": "平安"}},
                {"left": {"type": "text", "content": "危险"}, "right": {"type": "text", "content": "危急"}},
                {"left": {"type": "text", "content": "健康"}, "right": {"type": "text", "content": "强健"}},
                {"left": {"type": "text", "content": "生病"}, "right": {"type": "text", "content": "患病"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_025",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "开始"}, "right": {"type": "text", "content": "起始"}},
                {"left": {"type": "text", "content": "结束"}, "right": {"type": "text", "content": "完成"}},
                {"left": {"type": "text", "content": "继续"}, "right": {"type": "text", "content": "持续"}},
                {"left": {"type": "text", "content": "停止"}, "right": {"type": "text", "content": "停下"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_026",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "增加"}, "right": {"type": "text", "content": "增多"}},
                {"left": {"type": "text", "content": "减少"}, "right": {"type": "text", "content": "减小"}},
                {"left": {"type": "text", "content": "扩大"}, "right": {"type": "text", "content": "扩展"}},
                {"left": {"type": "text", "content": "缩小"}, "right": {"type": "text", "content": "缩减"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_027",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "提问"}, "right": {"type": "text", "content": "询问"}},
                {"left": {"type": "text", "content": "回答"}, "right": {"type": "text", "content": "解答"}},
                {"left": {"type": "text", "content": "讨论"}, "right": {"type": "text", "content": "商讨"}},
                {"left": {"type": "text", "content": "分享"}, "right": {"type": "text", "content": "共享"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_028",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "观察"}, "right": {"type": "text", "content": "观看"}},
                {"left": {"type": "text", "content": "思考"}, "right": {"type": "text", "content": "思索"}},
                {"left": {"type": "text", "content": "记忆"}, "right": {"type": "text", "content": "记住"}},
                {"left": {"type": "text", "content": "理解"}, "right": {"type": "text", "content": "明白"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_029",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "表达"}, "right": {"type": "text", "content": "表述"}},
                {"left": {"type": "text", "content": "描述"}, "right": {"type": "text", "content": "描写"}},
                {"left": {"type": "text", "content": "解释"}, "right": {"type": "text", "content": "说明"}},
                {"left": {"type": "text", "content": "介绍"}, "right": {"type": "text", "content": "推介"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_L2_030",
            "difficulty": "L2",
            "type": "text_text",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "合作"}, "right": {"type": "text", "content": "协作"}},
                {"left": {"type": "text", "content": "竞争"}, "right": {"type": "text", "content": "比赛"}},
                {"left": {"type": "text", "content": "支持"}, "right": {"type": "text", "content": "支援"}},
                {"left": {"type": "text", "content": "反对"}, "right": {"type": "text", "content": "抵制"}},
            ],
            "time_limit": 75,
        },
    ],
    "L3": [
        # 反义词连线 —— 共30题，每次随机抽10题
        {
            "id": "connect_L3_001",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "黑暗"}, "right": {"type": "text", "content": "光明"}},
                {"left": {"type": "text", "content": "寒冷"}, "right": {"type": "text", "content": "温暖"}},
                {"left": {"type": "text", "content": "喜欢"}, "right": {"type": "text", "content": "讨厌"}},
                {"left": {"type": "text", "content": "开始"}, "right": {"type": "text", "content": "结束"}},
                {"left": {"type": "text", "content": "胜利"}, "right": {"type": "text", "content": "失败"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_002",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "诚实"}, "right": {"type": "text", "content": "虚假"}},
                {"left": {"type": "text", "content": "努力"}, "right": {"type": "text", "content": "懒惰"}},
                {"left": {"type": "text", "content": "团结"}, "right": {"type": "text", "content": "分裂"}},
                {"left": {"type": "text", "content": "善良"}, "right": {"type": "text", "content": "凶恶"}},
                {"left": {"type": "text", "content": "宽容"}, "right": {"type": "text", "content": "苛刻"}},
                {"left": {"type": "text", "content": "谦虚"}, "right": {"type": "text", "content": "骄傲"}},
            ],
            "time_limit": 100,
        },
        {
            "id": "connect_L3_003",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "勤奋"}, "right": {"type": "text", "content": "懈怠"}},
                {"left": {"type": "text", "content": "慷慨"}, "right": {"type": "text", "content": "吝啬"}},
                {"left": {"type": "text", "content": "坚定"}, "right": {"type": "text", "content": "动摇"}},
                {"left": {"type": "text", "content": "乐观"}, "right": {"type": "text", "content": "悲观"}},
                {"left": {"type": "text", "content": "真诚"}, "right": {"type": "text", "content": "虚伪"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_004",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "聪慧"}, "right": {"type": "text", "content": "愚笨"}},
                {"left": {"type": "text", "content": "勇猛"}, "right": {"type": "text", "content": "懦弱"}},
                {"left": {"type": "text", "content": "繁荣"}, "right": {"type": "text", "content": "衰败"}},
                {"left": {"type": "text", "content": "和平"}, "right": {"type": "text", "content": "战争"}},
                {"left": {"type": "text", "content": "自由"}, "right": {"type": "text", "content": "束缚"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_005",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "高尚"}, "right": {"type": "text", "content": "卑鄙"}},
                {"left": {"type": "text", "content": "坚毅"}, "right": {"type": "text", "content": "软弱"}},
                {"left": {"type": "text", "content": "博学"}, "right": {"type": "text", "content": "无知"}},
                {"left": {"type": "text", "content": "公正"}, "right": {"type": "text", "content": "偏颇"}},
                {"left": {"type": "text", "content": "进步"}, "right": {"type": "text", "content": "退步"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_006",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "创新"}, "right": {"type": "text", "content": "守旧"}},
                {"left": {"type": "text", "content": "清廉"}, "right": {"type": "text", "content": "腐败"}},
                {"left": {"type": "text", "content": "奉献"}, "right": {"type": "text", "content": "自私"}},
                {"left": {"type": "text", "content": "包容"}, "right": {"type": "text", "content": "排斥"}},
                {"left": {"type": "text", "content": "勤劳"}, "right": {"type": "text", "content": "懒惰"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_007",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "快乐"}, "right": {"type": "text", "content": "痛苦"}},
                {"left": {"type": "text", "content": "希望"}, "right": {"type": "text", "content": "绝望"}},
                {"left": {"type": "text", "content": "成功"}, "right": {"type": "text", "content": "失败"}},
                {"left": {"type": "text", "content": "富裕"}, "right": {"type": "text", "content": "贫穷"}},
                {"left": {"type": "text", "content": "健康"}, "right": {"type": "text", "content": "病弱"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_008",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "聪明"}, "right": {"type": "text", "content": "愚蠢"}},
                {"left": {"type": "text", "content": "勤快"}, "right": {"type": "text", "content": "懒散"}},
                {"left": {"type": "text", "content": "整洁"}, "right": {"type": "text", "content": "凌乱"}},
                {"left": {"type": "text", "content": "安静"}, "right": {"type": "text", "content": "喧闹"}},
                {"left": {"type": "text", "content": "温暖"}, "right": {"type": "text", "content": "寒冷"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_009",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "明亮"}, "right": {"type": "text", "content": "黑暗"}},
                {"left": {"type": "text", "content": "宽阔"}, "right": {"type": "text", "content": "狭窄"}},
                {"left": {"type": "text", "content": "高大"}, "right": {"type": "text", "content": "矮小"}},
                {"left": {"type": "text", "content": "轻盈"}, "right": {"type": "text", "content": "沉重"}},
                {"left": {"type": "text", "content": "柔软"}, "right": {"type": "text", "content": "坚硬"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_010",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "增加"}, "right": {"type": "text", "content": "减少"}},
                {"left": {"type": "text", "content": "扩大"}, "right": {"type": "text", "content": "缩小"}},
                {"left": {"type": "text", "content": "提高"}, "right": {"type": "text", "content": "降低"}},
                {"left": {"type": "text", "content": "加速"}, "right": {"type": "text", "content": "减速"}},
                {"left": {"type": "text", "content": "前进"}, "right": {"type": "text", "content": "后退"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_011",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "接受"}, "right": {"type": "text", "content": "拒绝"}},
                {"left": {"type": "text", "content": "赞扬"}, "right": {"type": "text", "content": "批评"}},
                {"left": {"type": "text", "content": "奖励"}, "right": {"type": "text", "content": "惩罚"}},
                {"left": {"type": "text", "content": "信任"}, "right": {"type": "text", "content": "怀疑"}},
                {"left": {"type": "text", "content": "尊重"}, "right": {"type": "text", "content": "轻视"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_012",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "主动"}, "right": {"type": "text", "content": "被动"}},
                {"left": {"type": "text", "content": "积极"}, "right": {"type": "text", "content": "消极"}},
                {"left": {"type": "text", "content": "正面"}, "right": {"type": "text", "content": "负面"}},
                {"left": {"type": "text", "content": "优点"}, "right": {"type": "text", "content": "缺点"}},
                {"left": {"type": "text", "content": "长处"}, "right": {"type": "text", "content": "短处"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_013",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "开放"}, "right": {"type": "text", "content": "封闭"}},
                {"left": {"type": "text", "content": "公开"}, "right": {"type": "text", "content": "秘密"}},
                {"left": {"type": "text", "content": "透明"}, "right": {"type": "text", "content": "不透明"}},
                {"left": {"type": "text", "content": "简单"}, "right": {"type": "text", "content": "复杂"}},
                {"left": {"type": "text", "content": "清晰"}, "right": {"type": "text", "content": "模糊"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_014",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "有序"}, "right": {"type": "text", "content": "混乱"}},
                {"left": {"type": "text", "content": "规律"}, "right": {"type": "text", "content": "无序"}},
                {"left": {"type": "text", "content": "统一"}, "right": {"type": "text", "content": "分散"}},
                {"left": {"type": "text", "content": "集中"}, "right": {"type": "text", "content": "分散"}},
                {"left": {"type": "text", "content": "合并"}, "right": {"type": "text", "content": "分离"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_015",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "古老"}, "right": {"type": "text", "content": "现代"}},
                {"left": {"type": "text", "content": "传统"}, "right": {"type": "text", "content": "创新"}},
                {"left": {"type": "text", "content": "保守"}, "right": {"type": "text", "content": "开明"}},
                {"left": {"type": "text", "content": "落后"}, "right": {"type": "text", "content": "先进"}},
                {"left": {"type": "text", "content": "陈旧"}, "right": {"type": "text", "content": "新颖"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_016",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "坚硬"}, "right": {"type": "text", "content": "柔软"}},
                {"left": {"type": "text", "content": "粗糙"}, "right": {"type": "text", "content": "光滑"}},
                {"left": {"type": "text", "content": "干燥"}, "right": {"type": "text", "content": "湿润"}},
                {"left": {"type": "text", "content": "浓厚"}, "right": {"type": "text", "content": "稀薄"}},
                {"left": {"type": "text", "content": "沉重"}, "right": {"type": "text", "content": "轻盈"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_017",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "深刻"}, "right": {"type": "text", "content": "肤浅"}},
                {"left": {"type": "text", "content": "广博"}, "right": {"type": "text", "content": "狭隘"}},
                {"left": {"type": "text", "content": "精确"}, "right": {"type": "text", "content": "模糊"}},
                {"left": {"type": "text", "content": "严格"}, "right": {"type": "text", "content": "宽松"}},
                {"left": {"type": "text", "content": "细致"}, "right": {"type": "text", "content": "粗糙"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_018",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "勇敢"}, "right": {"type": "text", "content": "胆怯"}},
                {"left": {"type": "text", "content": "坚强"}, "right": {"type": "text", "content": "脆弱"}},
                {"left": {"type": "text", "content": "自信"}, "right": {"type": "text", "content": "自卑"}},
                {"left": {"type": "text", "content": "乐观"}, "right": {"type": "text", "content": "悲观"}},
                {"left": {"type": "text", "content": "开朗"}, "right": {"type": "text", "content": "内向"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_019",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "诚信"}, "right": {"type": "text", "content": "欺骗"}},
                {"left": {"type": "text", "content": "正直"}, "right": {"type": "text", "content": "奸诈"}},
                {"left": {"type": "text", "content": "廉洁"}, "right": {"type": "text", "content": "贪腐"}},
                {"left": {"type": "text", "content": "公平"}, "right": {"type": "text", "content": "不公"}},
                {"left": {"type": "text", "content": "守信"}, "right": {"type": "text", "content": "失信"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_020",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "热爱"}, "right": {"type": "text", "content": "厌恶"}},
                {"left": {"type": "text", "content": "珍视"}, "right": {"type": "text", "content": "轻视"}},
                {"left": {"type": "text", "content": "感恩"}, "right": {"type": "text", "content": "忘恩"}},
                {"left": {"type": "text", "content": "宽恕"}, "right": {"type": "text", "content": "记恨"}},
                {"left": {"type": "text", "content": "关爱"}, "right": {"type": "text", "content": "冷漠"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_021",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "节俭"}, "right": {"type": "text", "content": "奢侈"}},
                {"left": {"type": "text", "content": "朴素"}, "right": {"type": "text", "content": "华丽"}},
                {"left": {"type": "text", "content": "简朴"}, "right": {"type": "text", "content": "豪华"}},
                {"left": {"type": "text", "content": "节约"}, "right": {"type": "text", "content": "浪费"}},
                {"left": {"type": "text", "content": "勤俭"}, "right": {"type": "text", "content": "挥霍"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_022",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "团结"}, "right": {"type": "text", "content": "分裂"}},
                {"left": {"type": "text", "content": "合作"}, "right": {"type": "text", "content": "对抗"}},
                {"left": {"type": "text", "content": "友谊"}, "right": {"type": "text", "content": "敌意"}},
                {"left": {"type": "text", "content": "和谐"}, "right": {"type": "text", "content": "冲突"}},
                {"left": {"type": "text", "content": "互助"}, "right": {"type": "text", "content": "自私"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_023",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "认真"}, "right": {"type": "text", "content": "马虎"}},
                {"left": {"type": "text", "content": "细心"}, "right": {"type": "text", "content": "粗心"}},
                {"left": {"type": "text", "content": "专注"}, "right": {"type": "text", "content": "分心"}},
                {"left": {"type": "text", "content": "耐心"}, "right": {"type": "text", "content": "急躁"}},
                {"left": {"type": "text", "content": "踏实"}, "right": {"type": "text", "content": "浮躁"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_024",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "善始"}, "right": {"type": "text", "content": "善终"}},
                {"left": {"type": "text", "content": "有始"}, "right": {"type": "text", "content": "有终"}},
                {"left": {"type": "text", "content": "坚持"}, "right": {"type": "text", "content": "放弃"}},
                {"left": {"type": "text", "content": "完成"}, "right": {"type": "text", "content": "放弃"}},
                {"left": {"type": "text", "content": "成功"}, "right": {"type": "text", "content": "失败"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_025",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "理性"}, "right": {"type": "text", "content": "感性"}},
                {"left": {"type": "text", "content": "客观"}, "right": {"type": "text", "content": "主观"}},
                {"left": {"type": "text", "content": "抽象"}, "right": {"type": "text", "content": "具体"}},
                {"left": {"type": "text", "content": "宏观"}, "right": {"type": "text", "content": "微观"}},
                {"left": {"type": "text", "content": "整体"}, "right": {"type": "text", "content": "局部"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_026",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "原因"}, "right": {"type": "text", "content": "结果"}},
                {"left": {"type": "text", "content": "问题"}, "right": {"type": "text", "content": "答案"}},
                {"left": {"type": "text", "content": "条件"}, "right": {"type": "text", "content": "结论"}},
                {"left": {"type": "text", "content": "假设"}, "right": {"type": "text", "content": "验证"}},
                {"left": {"type": "text", "content": "理论"}, "right": {"type": "text", "content": "实践"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_027",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "付出"}, "right": {"type": "text", "content": "收获"}},
                {"left": {"type": "text", "content": "给予"}, "right": {"type": "text", "content": "索取"}},
                {"left": {"type": "text", "content": "奉献"}, "right": {"type": "text", "content": "索取"}},
                {"left": {"type": "text", "content": "贡献"}, "right": {"type": "text", "content": "享受"}},
                {"left": {"type": "text", "content": "劳动"}, "right": {"type": "text", "content": "享乐"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_028",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "记忆"}, "right": {"type": "text", "content": "遗忘"}},
                {"left": {"type": "text", "content": "铭记"}, "right": {"type": "text", "content": "淡忘"}},
                {"left": {"type": "text", "content": "珍藏"}, "right": {"type": "text", "content": "丢弃"}},
                {"left": {"type": "text", "content": "保留"}, "right": {"type": "text", "content": "舍弃"}},
                {"left": {"type": "text", "content": "传承"}, "right": {"type": "text", "content": "遗弃"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_029",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "建设"}, "right": {"type": "text", "content": "破坏"}},
                {"left": {"type": "text", "content": "保护"}, "right": {"type": "text", "content": "破坏"}},
                {"left": {"type": "text", "content": "创造"}, "right": {"type": "text", "content": "毁灭"}},
                {"left": {"type": "text", "content": "发展"}, "right": {"type": "text", "content": "衰退"}},
                {"left": {"type": "text", "content": "兴盛"}, "right": {"type": "text", "content": "衰落"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_L3_030",
            "difficulty": "L3",
            "type": "text_text",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "光荣"}, "right": {"type": "text", "content": "耻辱"}},
                {"left": {"type": "text", "content": "荣誉"}, "right": {"type": "text", "content": "耻辱"}},
                {"left": {"type": "text", "content": "骄傲"}, "right": {"type": "text", "content": "羞耻"}},
                {"left": {"type": "text", "content": "自豪"}, "right": {"type": "text", "content": "惭愧"}},
                {"left": {"type": "text", "content": "赞美"}, "right": {"type": "text", "content": "批评"}},
            ],
            "time_limit": 90,
        },
    ],
}


def get_questions(difficulty: str) -> List[Dict[str, Any]]:
    """返回指定难度的全部连一连题目列表。"""
    return CONNECT_QUESTIONS.get(difficulty, [])


# ── 关卡专用题目数据 ──────────────────────────────────────────────────────────

CONNECT_LEVEL_QUESTIONS: dict = {
    "L1": [
        {
            "id": "connect_lv_L1_001",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "山"}, "right": {"type": "text", "content": "山"}},
                {"left": {"type": "text", "content": "水"}, "right": {"type": "text", "content": "水"}},
                {"left": {"type": "text", "content": "日"}, "right": {"type": "text", "content": "日"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_002",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "月"}, "right": {"type": "text", "content": "月"}},
                {"left": {"type": "text", "content": "火"}, "right": {"type": "text", "content": "火"}},
                {"left": {"type": "text", "content": "木"}, "right": {"type": "text", "content": "木"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_003",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "土"}, "right": {"type": "text", "content": "土"}},
                {"left": {"type": "text", "content": "金"}, "right": {"type": "text", "content": "金"}},
                {"left": {"type": "text", "content": "风"}, "right": {"type": "text", "content": "风"}},
                {"left": {"type": "text", "content": "云"}, "right": {"type": "text", "content": "云"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_004",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "花"}, "right": {"type": "text", "content": "花"}},
                {"left": {"type": "text", "content": "草"}, "right": {"type": "text", "content": "草"}},
                {"left": {"type": "text", "content": "鸟"}, "right": {"type": "text", "content": "鸟"}},
                {"left": {"type": "text", "content": "鱼"}, "right": {"type": "text", "content": "鱼"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_005",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "猫"}, "right": {"type": "text", "content": "猫"}},
                {"left": {"type": "text", "content": "狗"}, "right": {"type": "text", "content": "狗"}},
                {"left": {"type": "text", "content": "牛"}, "right": {"type": "text", "content": "牛"}},
                {"left": {"type": "text", "content": "羊"}, "right": {"type": "text", "content": "羊"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_006",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "大"}, "right": {"type": "text", "content": "大"}},
                {"left": {"type": "text", "content": "小"}, "right": {"type": "text", "content": "小"}},
                {"left": {"type": "text", "content": "上"}, "right": {"type": "text", "content": "上"}},
                {"left": {"type": "text", "content": "下"}, "right": {"type": "text", "content": "下"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_007",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "红"}, "right": {"type": "text", "content": "红"}},
                {"left": {"type": "text", "content": "蓝"}, "right": {"type": "text", "content": "蓝"}},
                {"left": {"type": "text", "content": "绿"}, "right": {"type": "text", "content": "绿"}},
                {"left": {"type": "text", "content": "黄"}, "right": {"type": "text", "content": "黄"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_008",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "一"}, "right": {"type": "text", "content": "一"}},
                {"left": {"type": "text", "content": "二"}, "right": {"type": "text", "content": "二"}},
                {"left": {"type": "text", "content": "三"}, "right": {"type": "text", "content": "三"}},
                {"left": {"type": "text", "content": "四"}, "right": {"type": "text", "content": "四"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_009",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "春"}, "right": {"type": "text", "content": "春"}},
                {"left": {"type": "text", "content": "夏"}, "right": {"type": "text", "content": "夏"}},
                {"left": {"type": "text", "content": "秋"}, "right": {"type": "text", "content": "秋"}},
                {"left": {"type": "text", "content": "冬"}, "right": {"type": "text", "content": "冬"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_010",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "东"}, "right": {"type": "text", "content": "东"}},
                {"left": {"type": "text", "content": "西"}, "right": {"type": "text", "content": "西"}},
                {"left": {"type": "text", "content": "南"}, "right": {"type": "text", "content": "南"}},
                {"left": {"type": "text", "content": "北"}, "right": {"type": "text", "content": "北"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_011",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "人"}, "right": {"type": "text", "content": "人"}},
                {"left": {"type": "text", "content": "口"}, "right": {"type": "text", "content": "口"}},
                {"left": {"type": "text", "content": "手"}, "right": {"type": "text", "content": "手"}},
                {"left": {"type": "text", "content": "目"}, "right": {"type": "text", "content": "目"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_012",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "书"}, "right": {"type": "text", "content": "书"}},
                {"left": {"type": "text", "content": "笔"}, "right": {"type": "text", "content": "笔"}},
                {"left": {"type": "text", "content": "纸"}, "right": {"type": "text", "content": "纸"}},
                {"left": {"type": "text", "content": "字"}, "right": {"type": "text", "content": "字"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_013",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "天"}, "right": {"type": "text", "content": "天"}},
                {"left": {"type": "text", "content": "地"}, "right": {"type": "text", "content": "地"}},
                {"left": {"type": "text", "content": "家"}, "right": {"type": "text", "content": "家"}},
                {"left": {"type": "text", "content": "国"}, "right": {"type": "text", "content": "国"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_014",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "爸"}, "right": {"type": "text", "content": "爸"}},
                {"left": {"type": "text", "content": "妈"}, "right": {"type": "text", "content": "妈"}},
                {"left": {"type": "text", "content": "哥"}, "right": {"type": "text", "content": "哥"}},
                {"left": {"type": "text", "content": "姐"}, "right": {"type": "text", "content": "姐"}},
            ],
            "time_limit": 60,
        },
        {
            "id": "connect_lv_L1_015",
            "type": "connect_pairs",
            "difficulty": "L1",
            "title": "连一连",
            "instruction": "把相同的字连起来",
            "pairs": [
                {"left": {"type": "text", "content": "好"}, "right": {"type": "text", "content": "好"}},
                {"left": {"type": "text", "content": "多"}, "right": {"type": "text", "content": "多"}},
                {"left": {"type": "text", "content": "快"}, "right": {"type": "text", "content": "快"}},
                {"left": {"type": "text", "content": "乐"}, "right": {"type": "text", "content": "乐"}},
            ],
            "time_limit": 60,
        },
    ],
    "L2": [
        {
            "id": "connect_lv_L2_001",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "高兴"}, "right": {"type": "text", "content": "快乐"}},
                {"left": {"type": "text", "content": "漂亮"}, "right": {"type": "text", "content": "美丽"}},
                {"left": {"type": "text", "content": "害怕"}, "right": {"type": "text", "content": "恐惧"}},
                {"left": {"type": "text", "content": "聪明"}, "right": {"type": "text", "content": "智慧"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_002",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "勇敢"}, "right": {"type": "text", "content": "胆大"}},
                {"left": {"type": "text", "content": "悲伤"}, "right": {"type": "text", "content": "难过"}},
                {"left": {"type": "text", "content": "奔跑"}, "right": {"type": "text", "content": "飞奔"}},
                {"left": {"type": "text", "content": "帮助"}, "right": {"type": "text", "content": "援助"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_003",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "寻找"}, "right": {"type": "text", "content": "寻觅"}},
                {"left": {"type": "text", "content": "开心"}, "right": {"type": "text", "content": "愉快"}},
                {"left": {"type": "text", "content": "温柔"}, "right": {"type": "text", "content": "温和"}},
                {"left": {"type": "text", "content": "坚强"}, "right": {"type": "text", "content": "坚韧"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_004",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "宽广"}, "right": {"type": "text", "content": "辽阔"}},
                {"left": {"type": "text", "content": "清晰"}, "right": {"type": "text", "content": "清楚"}},
                {"left": {"type": "text", "content": "珍贵"}, "right": {"type": "text", "content": "宝贵"}},
                {"left": {"type": "text", "content": "迅速"}, "right": {"type": "text", "content": "快速"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_005",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "欢喜"}, "right": {"type": "text", "content": "喜悦"}},
                {"left": {"type": "text", "content": "忧愁"}, "right": {"type": "text", "content": "忧郁"}},
                {"left": {"type": "text", "content": "明亮"}, "right": {"type": "text", "content": "光亮"}},
                {"left": {"type": "text", "content": "柔软"}, "right": {"type": "text", "content": "柔和"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_006",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "仔细"}, "right": {"type": "text", "content": "认真"}},
                {"left": {"type": "text", "content": "喜爱"}, "right": {"type": "text", "content": "热爱"}},
                {"left": {"type": "text", "content": "担心"}, "right": {"type": "text", "content": "忧虑"}},
                {"left": {"type": "text", "content": "奇怪"}, "right": {"type": "text", "content": "奇特"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_007",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "保护"}, "right": {"type": "text", "content": "守护"}},
                {"left": {"type": "text", "content": "美好"}, "right": {"type": "text", "content": "美妙"}},
                {"left": {"type": "text", "content": "快活"}, "right": {"type": "text", "content": "欢乐"}},
                {"left": {"type": "text", "content": "勤劳"}, "right": {"type": "text", "content": "勤奋"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_008",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "温暖"}, "right": {"type": "text", "content": "暖和"}},
                {"left": {"type": "text", "content": "清凉"}, "right": {"type": "text", "content": "凉爽"}},
                {"left": {"type": "text", "content": "广阔"}, "right": {"type": "text", "content": "宽阔"}},
                {"left": {"type": "text", "content": "著名"}, "right": {"type": "text", "content": "有名"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_009",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "容易"}, "right": {"type": "text", "content": "简单"}},
                {"left": {"type": "text", "content": "困难"}, "right": {"type": "text", "content": "艰难"}},
                {"left": {"type": "text", "content": "期待"}, "right": {"type": "text", "content": "盼望"}},
                {"left": {"type": "text", "content": "惊讶"}, "right": {"type": "text", "content": "惊奇"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_010",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "感谢"}, "right": {"type": "text", "content": "感激"}},
                {"left": {"type": "text", "content": "平静"}, "right": {"type": "text", "content": "平和"}},
                {"left": {"type": "text", "content": "疲惫"}, "right": {"type": "text", "content": "疲倦"}},
                {"left": {"type": "text", "content": "聪慧"}, "right": {"type": "text", "content": "机智"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_011",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "正确"}, "right": {"type": "text", "content": "准确"}},
                {"left": {"type": "text", "content": "完整"}, "right": {"type": "text", "content": "完全"}},
                {"left": {"type": "text", "content": "特别"}, "right": {"type": "text", "content": "特殊"}},
                {"left": {"type": "text", "content": "重要"}, "right": {"type": "text", "content": "重大"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_012",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "坚持"}, "right": {"type": "text", "content": "坚守"}},
                {"left": {"type": "text", "content": "丰富"}, "right": {"type": "text", "content": "充足"}},
                {"left": {"type": "text", "content": "善意"}, "right": {"type": "text", "content": "好意"}},
                {"left": {"type": "text", "content": "聪颖"}, "right": {"type": "text", "content": "聪明"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_013",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "高大"}, "right": {"type": "text", "content": "高耸"}},
                {"left": {"type": "text", "content": "微小"}, "right": {"type": "text", "content": "细小"}},
                {"left": {"type": "text", "content": "鲜艳"}, "right": {"type": "text", "content": "艳丽"}},
                {"left": {"type": "text", "content": "普通"}, "right": {"type": "text", "content": "平常"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_014",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "思念"}, "right": {"type": "text", "content": "想念"}},
                {"left": {"type": "text", "content": "珍贵"}, "right": {"type": "text", "content": "宝贵"}},
                {"left": {"type": "text", "content": "迅速"}, "right": {"type": "text", "content": "快速"}},
                {"left": {"type": "text", "content": "安静"}, "right": {"type": "text", "content": "宁静"}},
            ],
            "time_limit": 75,
        },
        {
            "id": "connect_lv_L2_015",
            "type": "connect_pairs",
            "difficulty": "L2",
            "title": "连一连",
            "instruction": "把意思相近的词语连起来",
            "pairs": [
                {"left": {"type": "text", "content": "害怕"}, "right": {"type": "text", "content": "恐惧"}},
                {"left": {"type": "text", "content": "聪明"}, "right": {"type": "text", "content": "智慧"}},
                {"left": {"type": "text", "content": "勇敢"}, "right": {"type": "text", "content": "胆大"}},
                {"left": {"type": "text", "content": "悲伤"}, "right": {"type": "text", "content": "难过"}},
            ],
            "time_limit": 75,
        },
    ],
    "L3": [
        {
            "id": "connect_lv_L3_001",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "黑暗"}, "right": {"type": "text", "content": "光明"}},
                {"left": {"type": "text", "content": "寒冷"}, "right": {"type": "text", "content": "温暖"}},
                {"left": {"type": "text", "content": "喜欢"}, "right": {"type": "text", "content": "讨厌"}},
                {"left": {"type": "text", "content": "开始"}, "right": {"type": "text", "content": "结束"}},
                {"left": {"type": "text", "content": "胜利"}, "right": {"type": "text", "content": "失败"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_002",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "诚实"}, "right": {"type": "text", "content": "虚假"}},
                {"left": {"type": "text", "content": "努力"}, "right": {"type": "text", "content": "懒惰"}},
                {"left": {"type": "text", "content": "团结"}, "right": {"type": "text", "content": "分裂"}},
                {"left": {"type": "text", "content": "善良"}, "right": {"type": "text", "content": "凶恶"}},
                {"left": {"type": "text", "content": "谦虚"}, "right": {"type": "text", "content": "骄傲"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_003",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "宽容"}, "right": {"type": "text", "content": "苛刻"}},
                {"left": {"type": "text", "content": "勤奋"}, "right": {"type": "text", "content": "懈怠"}},
                {"left": {"type": "text", "content": "慷慨"}, "right": {"type": "text", "content": "吝啬"}},
                {"left": {"type": "text", "content": "坚定"}, "right": {"type": "text", "content": "动摇"}},
                {"left": {"type": "text", "content": "乐观"}, "right": {"type": "text", "content": "悲观"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_004",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "聪慧"}, "right": {"type": "text", "content": "愚笨"}},
                {"left": {"type": "text", "content": "勇猛"}, "right": {"type": "text", "content": "懦弱"}},
                {"left": {"type": "text", "content": "繁荣"}, "right": {"type": "text", "content": "衰败"}},
                {"left": {"type": "text", "content": "和平"}, "right": {"type": "text", "content": "战争"}},
                {"left": {"type": "text", "content": "自由"}, "right": {"type": "text", "content": "束缚"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_005",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "高尚"}, "right": {"type": "text", "content": "卑鄙"}},
                {"left": {"type": "text", "content": "坚毅"}, "right": {"type": "text", "content": "软弱"}},
                {"left": {"type": "text", "content": "博学"}, "right": {"type": "text", "content": "无知"}},
                {"left": {"type": "text", "content": "公正"}, "right": {"type": "text", "content": "偏颇"}},
                {"left": {"type": "text", "content": "进步"}, "right": {"type": "text", "content": "退步"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_006",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "大"}, "right": {"type": "text", "content": "小"}},
                {"left": {"type": "text", "content": "快"}, "right": {"type": "text", "content": "慢"}},
                {"left": {"type": "text", "content": "冷"}, "right": {"type": "text", "content": "热"}},
                {"left": {"type": "text", "content": "高"}, "right": {"type": "text", "content": "低"}},
                {"left": {"type": "text", "content": "多"}, "right": {"type": "text", "content": "少"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_007",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "来"}, "right": {"type": "text", "content": "去"}},
                {"left": {"type": "text", "content": "开"}, "right": {"type": "text", "content": "关"}},
                {"left": {"type": "text", "content": "买"}, "right": {"type": "text", "content": "卖"}},
                {"left": {"type": "text", "content": "哭"}, "right": {"type": "text", "content": "笑"}},
                {"left": {"type": "text", "content": "爱"}, "right": {"type": "text", "content": "恨"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_008",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "长"}, "right": {"type": "text", "content": "短"}},
                {"left": {"type": "text", "content": "早"}, "right": {"type": "text", "content": "晚"}},
                {"left": {"type": "text", "content": "前"}, "right": {"type": "text", "content": "后"}},
                {"left": {"type": "text", "content": "左"}, "right": {"type": "text", "content": "右"}},
                {"left": {"type": "text", "content": "上"}, "right": {"type": "text", "content": "下"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_009",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "明"}, "right": {"type": "text", "content": "暗"}},
                {"left": {"type": "text", "content": "干"}, "right": {"type": "text", "content": "湿"}},
                {"left": {"type": "text", "content": "真"}, "right": {"type": "text", "content": "假"}},
                {"left": {"type": "text", "content": "对"}, "right": {"type": "text", "content": "错"}},
                {"left": {"type": "text", "content": "美"}, "right": {"type": "text", "content": "丑"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_010",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "胖"}, "right": {"type": "text", "content": "瘦"}},
                {"left": {"type": "text", "content": "深"}, "right": {"type": "text", "content": "浅"}},
                {"left": {"type": "text", "content": "粗"}, "right": {"type": "text", "content": "细"}},
                {"left": {"type": "text", "content": "软"}, "right": {"type": "text", "content": "硬"}},
                {"left": {"type": "text", "content": "轻"}, "right": {"type": "text", "content": "重"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_011",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "清廉"}, "right": {"type": "text", "content": "腐败"}},
                {"left": {"type": "text", "content": "奉献"}, "right": {"type": "text", "content": "自私"}},
                {"left": {"type": "text", "content": "包容"}, "right": {"type": "text", "content": "排斥"}},
                {"left": {"type": "text", "content": "繁荣"}, "right": {"type": "text", "content": "衰败"}},
                {"left": {"type": "text", "content": "和平"}, "right": {"type": "text", "content": "战争"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_012",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "新"}, "right": {"type": "text", "content": "旧"}},
                {"left": {"type": "text", "content": "好"}, "right": {"type": "text", "content": "坏"}},
                {"left": {"type": "text", "content": "甜"}, "right": {"type": "text", "content": "苦"}},
                {"left": {"type": "text", "content": "胜"}, "right": {"type": "text", "content": "败"}},
                {"left": {"type": "text", "content": "进"}, "right": {"type": "text", "content": "退"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_013",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "真诚"}, "right": {"type": "text", "content": "虚伪"}},
                {"left": {"type": "text", "content": "乐观"}, "right": {"type": "text", "content": "悲观"}},
                {"left": {"type": "text", "content": "坚定"}, "right": {"type": "text", "content": "动摇"}},
                {"left": {"type": "text", "content": "慷慨"}, "right": {"type": "text", "content": "吝啬"}},
                {"left": {"type": "text", "content": "勤奋"}, "right": {"type": "text", "content": "懈怠"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_014",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "聪慧"}, "right": {"type": "text", "content": "愚笨"}},
                {"left": {"type": "text", "content": "勇猛"}, "right": {"type": "text", "content": "懦弱"}},
                {"left": {"type": "text", "content": "善良"}, "right": {"type": "text", "content": "凶恶"}},
                {"left": {"type": "text", "content": "谦虚"}, "right": {"type": "text", "content": "骄傲"}},
                {"left": {"type": "text", "content": "宽容"}, "right": {"type": "text", "content": "苛刻"}},
            ],
            "time_limit": 90,
        },
        {
            "id": "connect_lv_L3_015",
            "type": "connect_pairs",
            "difficulty": "L3",
            "title": "连一连",
            "instruction": "把反义词连起来",
            "pairs": [
                {"left": {"type": "text", "content": "黑暗"}, "right": {"type": "text", "content": "光明"}},
                {"left": {"type": "text", "content": "寒冷"}, "right": {"type": "text", "content": "温暖"}},
                {"left": {"type": "text", "content": "喜欢"}, "right": {"type": "text", "content": "讨厌"}},
                {"left": {"type": "text", "content": "开始"}, "right": {"type": "text", "content": "结束"}},
                {"left": {"type": "text", "content": "胜利"}, "right": {"type": "text", "content": "失败"}},
            ],
            "time_limit": 90,
        },
    ],
}

# ── 关卡数据 ──────────────────────────────────────────────────────────────────

CONNECT_GAME_LEVELS: dict = {
    "L1": [
        {
            "level_id": "connect_game_L1_lv1",
            "level_num": 1,
            "title": "第1关",
            "difficulty": "L1",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L1"][0]],
        },
        {
            "level_id": "connect_game_L1_lv2",
            "level_num": 2,
            "title": "第2关",
            "difficulty": "L1",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L1"][1]],
        },
        {
            "level_id": "connect_game_L1_lv3",
            "level_num": 3,
            "title": "第3关",
            "difficulty": "L1",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L1"][2]],
        },
        {
            "level_id": "connect_game_L1_lv4",
            "level_num": 4,
            "title": "第4关",
            "difficulty": "L1",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L1"][3]],
        },
        {
            "level_id": "connect_game_L1_lv5",
            "level_num": 5,
            "title": "第5关",
            "difficulty": "L1",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L1"][4]],
        },
    ],
    "L2": [
        {
            "level_id": "connect_game_L2_lv1",
            "level_num": 1,
            "title": "第1关",
            "difficulty": "L2",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L2"][0]],
        },
        {
            "level_id": "connect_game_L2_lv2",
            "level_num": 2,
            "title": "第2关",
            "difficulty": "L2",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L2"][1]],
        },
        {
            "level_id": "connect_game_L2_lv3",
            "level_num": 3,
            "title": "第3关",
            "difficulty": "L2",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L2"][2]],
        },
        {
            "level_id": "connect_game_L2_lv4",
            "level_num": 4,
            "title": "第4关",
            "difficulty": "L2",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L2"][3]],
        },
        {
            "level_id": "connect_game_L2_lv5",
            "level_num": 5,
            "title": "第5关",
            "difficulty": "L2",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L2"][4]],
        },
    ],
    "L3": [
        {
            "level_id": "connect_game_L3_lv1",
            "level_num": 1,
            "title": "第1关",
            "difficulty": "L3",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L3"][0]],
        },
        {
            "level_id": "connect_game_L3_lv2",
            "level_num": 2,
            "title": "第2关",
            "difficulty": "L3",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L3"][1]],
        },
        {
            "level_id": "connect_game_L3_lv3",
            "level_num": 3,
            "title": "第3关",
            "difficulty": "L3",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L3"][2]],
        },
        {
            "level_id": "connect_game_L3_lv4",
            "level_num": 4,
            "title": "第4关",
            "difficulty": "L3",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L3"][3]],
        },
        {
            "level_id": "connect_game_L3_lv5",
            "level_num": 5,
            "title": "第5关",
            "difficulty": "L3",
            "game_type": "connect_game",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["connect_pairs"],
            "questions": [CONNECT_LEVEL_QUESTIONS["L3"][4]],
        },
    ],
}
