"""
翻牌记忆游戏题库（以阅读为主，全文字内容）
难度分级：
  L1 — 8 张（4 对），汉字-汉字配对（相同汉字）
  L2 — 12 张（6 对），词语-词语配对（近义词）
  L3 — 16 张（8 对），词语-词语配对（反义词/关联词）
"""
import random
from typing import List, Dict, Any

# 原始牌组定义（每个 pair 包含两张卡的内容，全部为文字）
FLIP_CARD_DECKS: Dict[str, List[Dict[str, Any]]] = {
    "L1": [
        # 相同汉字配对（认字练习）—— 共30对，每次随机抽10对
        {"pair_id": "L1_p01", "card_a": {"type": "text", "content": "山"}, "card_b": {"type": "text", "content": "山"}},
        {"pair_id": "L1_p02", "card_a": {"type": "text", "content": "水"}, "card_b": {"type": "text", "content": "水"}},
        {"pair_id": "L1_p03", "card_a": {"type": "text", "content": "日"}, "card_b": {"type": "text", "content": "日"}},
        {"pair_id": "L1_p04", "card_a": {"type": "text", "content": "月"}, "card_b": {"type": "text", "content": "月"}},
        {"pair_id": "L1_p05", "card_a": {"type": "text", "content": "火"}, "card_b": {"type": "text", "content": "火"}},
        {"pair_id": "L1_p06", "card_a": {"type": "text", "content": "木"}, "card_b": {"type": "text", "content": "木"}},
        {"pair_id": "L1_p07", "card_a": {"type": "text", "content": "土"}, "card_b": {"type": "text", "content": "土"}},
        {"pair_id": "L1_p08", "card_a": {"type": "text", "content": "金"}, "card_b": {"type": "text", "content": "金"}},
        {"pair_id": "L1_p09", "card_a": {"type": "text", "content": "风"}, "card_b": {"type": "text", "content": "风"}},
        {"pair_id": "L1_p10", "card_a": {"type": "text", "content": "云"}, "card_b": {"type": "text", "content": "云"}},
        {"pair_id": "L1_p11", "card_a": {"type": "text", "content": "花"}, "card_b": {"type": "text", "content": "花"}},
        {"pair_id": "L1_p12", "card_a": {"type": "text", "content": "草"}, "card_b": {"type": "text", "content": "草"}},
        {"pair_id": "L1_p13", "card_a": {"type": "text", "content": "鸟"}, "card_b": {"type": "text", "content": "鸟"}},
        {"pair_id": "L1_p14", "card_a": {"type": "text", "content": "鱼"}, "card_b": {"type": "text", "content": "鱼"}},
        {"pair_id": "L1_p15", "card_a": {"type": "text", "content": "猫"}, "card_b": {"type": "text", "content": "猫"}},
        {"pair_id": "L1_p16", "card_a": {"type": "text", "content": "狗"}, "card_b": {"type": "text", "content": "狗"}},
        {"pair_id": "L1_p17", "card_a": {"type": "text", "content": "牛"}, "card_b": {"type": "text", "content": "牛"}},
        {"pair_id": "L1_p18", "card_a": {"type": "text", "content": "羊"}, "card_b": {"type": "text", "content": "羊"}},
        {"pair_id": "L1_p19", "card_a": {"type": "text", "content": "马"}, "card_b": {"type": "text", "content": "马"}},
        {"pair_id": "L1_p20", "card_a": {"type": "text", "content": "虎"}, "card_b": {"type": "text", "content": "虎"}},
        {"pair_id": "L1_p21", "card_a": {"type": "text", "content": "大"}, "card_b": {"type": "text", "content": "大"}},
        {"pair_id": "L1_p22", "card_a": {"type": "text", "content": "小"}, "card_b": {"type": "text", "content": "小"}},
        {"pair_id": "L1_p23", "card_a": {"type": "text", "content": "上"}, "card_b": {"type": "text", "content": "上"}},
        {"pair_id": "L1_p24", "card_a": {"type": "text", "content": "下"}, "card_b": {"type": "text", "content": "下"}},
        {"pair_id": "L1_p25", "card_a": {"type": "text", "content": "左"}, "card_b": {"type": "text", "content": "左"}},
        {"pair_id": "L1_p26", "card_a": {"type": "text", "content": "右"}, "card_b": {"type": "text", "content": "右"}},
        {"pair_id": "L1_p27", "card_a": {"type": "text", "content": "红"}, "card_b": {"type": "text", "content": "红"}},
        {"pair_id": "L1_p28", "card_a": {"type": "text", "content": "蓝"}, "card_b": {"type": "text", "content": "蓝"}},
        {"pair_id": "L1_p29", "card_a": {"type": "text", "content": "绿"}, "card_b": {"type": "text", "content": "绿"}},
        {"pair_id": "L1_p30", "card_a": {"type": "text", "content": "黄"}, "card_b": {"type": "text", "content": "黄"}},
    ],
    "L2": [
        # 近义词配对 —— 共30对，每次随机抽10对
        {"pair_id": "L2_p01", "card_a": {"type": "text", "content": "高兴"}, "card_b": {"type": "text", "content": "快乐"}},
        {"pair_id": "L2_p02", "card_a": {"type": "text", "content": "漂亮"}, "card_b": {"type": "text", "content": "美丽"}},
        {"pair_id": "L2_p03", "card_a": {"type": "text", "content": "害怕"}, "card_b": {"type": "text", "content": "恐惧"}},
        {"pair_id": "L2_p04", "card_a": {"type": "text", "content": "聪明"}, "card_b": {"type": "text", "content": "智慧"}},
        {"pair_id": "L2_p05", "card_a": {"type": "text", "content": "勇敢"}, "card_b": {"type": "text", "content": "胆大"}},
        {"pair_id": "L2_p06", "card_a": {"type": "text", "content": "悲伤"}, "card_b": {"type": "text", "content": "难过"}},
        {"pair_id": "L2_p07", "card_a": {"type": "text", "content": "奔跑"}, "card_b": {"type": "text", "content": "飞奔"}},
        {"pair_id": "L2_p08", "card_a": {"type": "text", "content": "帮助"}, "card_b": {"type": "text", "content": "援助"}},
        {"pair_id": "L2_p09", "card_a": {"type": "text", "content": "寻找"}, "card_b": {"type": "text", "content": "寻觅"}},
        {"pair_id": "L2_p10", "card_a": {"type": "text", "content": "开心"}, "card_b": {"type": "text", "content": "愉快"}},
        {"pair_id": "L2_p11", "card_a": {"type": "text", "content": "温柔"}, "card_b": {"type": "text", "content": "温和"}},
        {"pair_id": "L2_p12", "card_a": {"type": "text", "content": "坚强"}, "card_b": {"type": "text", "content": "坚韧"}},
        {"pair_id": "L2_p13", "card_a": {"type": "text", "content": "思念"}, "card_b": {"type": "text", "content": "想念"}},
        {"pair_id": "L2_p14", "card_a": {"type": "text", "content": "宽广"}, "card_b": {"type": "text", "content": "辽阔"}},
        {"pair_id": "L2_p15", "card_a": {"type": "text", "content": "清晰"}, "card_b": {"type": "text", "content": "清楚"}},
        {"pair_id": "L2_p16", "card_a": {"type": "text", "content": "珍贵"}, "card_b": {"type": "text", "content": "宝贵"}},
        {"pair_id": "L2_p17", "card_a": {"type": "text", "content": "迅速"}, "card_b": {"type": "text", "content": "快速"}},
        {"pair_id": "L2_p18", "card_a": {"type": "text", "content": "安静"}, "card_b": {"type": "text", "content": "宁静"}},
        {"pair_id": "L2_p19", "card_a": {"type": "text", "content": "欢喜"}, "card_b": {"type": "text", "content": "喜悦"}},
        {"pair_id": "L2_p20", "card_a": {"type": "text", "content": "忧愁"}, "card_b": {"type": "text", "content": "忧郁"}},
        {"pair_id": "L2_p21", "card_a": {"type": "text", "content": "明亮"}, "card_b": {"type": "text", "content": "光亮"}},
        {"pair_id": "L2_p22", "card_a": {"type": "text", "content": "柔软"}, "card_b": {"type": "text", "content": "柔和"}},
        {"pair_id": "L2_p23", "card_a": {"type": "text", "content": "强壮"}, "card_b": {"type": "text", "content": "健壮"}},
        {"pair_id": "L2_p24", "card_a": {"type": "text", "content": "仔细"}, "card_b": {"type": "text", "content": "认真"}},
        {"pair_id": "L2_p25", "card_a": {"type": "text", "content": "喜爱"}, "card_b": {"type": "text", "content": "热爱"}},
        {"pair_id": "L2_p26", "card_a": {"type": "text", "content": "担心"}, "card_b": {"type": "text", "content": "忧虑"}},
        {"pair_id": "L2_p27", "card_a": {"type": "text", "content": "奇怪"}, "card_b": {"type": "text", "content": "奇特"}},
        {"pair_id": "L2_p28", "card_a": {"type": "text", "content": "整洁"}, "card_b": {"type": "text", "content": "干净"}},
        {"pair_id": "L2_p29", "card_a": {"type": "text", "content": "疲惫"}, "card_b": {"type": "text", "content": "疲倦"}},
        {"pair_id": "L2_p30", "card_a": {"type": "text", "content": "聪慧"}, "card_b": {"type": "text", "content": "机智"}},
    ],
    "L3": [
        # 反义词配对 —— 共30对，每次随机抽10对
        {"pair_id": "L3_p01", "card_a": {"type": "text", "content": "黑暗"}, "card_b": {"type": "text", "content": "光明"}},
        {"pair_id": "L3_p02", "card_a": {"type": "text", "content": "寒冷"}, "card_b": {"type": "text", "content": "温暖"}},
        {"pair_id": "L3_p03", "card_a": {"type": "text", "content": "喜欢"}, "card_b": {"type": "text", "content": "讨厌"}},
        {"pair_id": "L3_p04", "card_a": {"type": "text", "content": "开始"}, "card_b": {"type": "text", "content": "结束"}},
        {"pair_id": "L3_p05", "card_a": {"type": "text", "content": "胜利"}, "card_b": {"type": "text", "content": "失败"}},
        {"pair_id": "L3_p06", "card_a": {"type": "text", "content": "诚实"}, "card_b": {"type": "text", "content": "虚假"}},
        {"pair_id": "L3_p07", "card_a": {"type": "text", "content": "努力"}, "card_b": {"type": "text", "content": "懒惰"}},
        {"pair_id": "L3_p08", "card_a": {"type": "text", "content": "团结"}, "card_b": {"type": "text", "content": "分裂"}},
        {"pair_id": "L3_p09", "card_a": {"type": "text", "content": "善良"}, "card_b": {"type": "text", "content": "凶恶"}},
        {"pair_id": "L3_p10", "card_a": {"type": "text", "content": "谦虚"}, "card_b": {"type": "text", "content": "骄傲"}},
        {"pair_id": "L3_p11", "card_a": {"type": "text", "content": "宽容"}, "card_b": {"type": "text", "content": "苛刻"}},
        {"pair_id": "L3_p12", "card_a": {"type": "text", "content": "勤奋"}, "card_b": {"type": "text", "content": "懈怠"}},
        {"pair_id": "L3_p13", "card_a": {"type": "text", "content": "慷慨"}, "card_b": {"type": "text", "content": "吝啬"}},
        {"pair_id": "L3_p14", "card_a": {"type": "text", "content": "坚定"}, "card_b": {"type": "text", "content": "动摇"}},
        {"pair_id": "L3_p15", "card_a": {"type": "text", "content": "乐观"}, "card_b": {"type": "text", "content": "悲观"}},
        {"pair_id": "L3_p16", "card_a": {"type": "text", "content": "真诚"}, "card_b": {"type": "text", "content": "虚伪"}},
        {"pair_id": "L3_p17", "card_a": {"type": "text", "content": "聪慧"}, "card_b": {"type": "text", "content": "愚笨"}},
        {"pair_id": "L3_p18", "card_a": {"type": "text", "content": "勇猛"}, "card_b": {"type": "text", "content": "懦弱"}},
        {"pair_id": "L3_p19", "card_a": {"type": "text", "content": "繁荣"}, "card_b": {"type": "text", "content": "衰败"}},
        {"pair_id": "L3_p20", "card_a": {"type": "text", "content": "和平"}, "card_b": {"type": "text", "content": "战争"}},
        {"pair_id": "L3_p21", "card_a": {"type": "text", "content": "自由"}, "card_b": {"type": "text", "content": "束缚"}},
        {"pair_id": "L3_p22", "card_a": {"type": "text", "content": "高尚"}, "card_b": {"type": "text", "content": "卑鄙"}},
        {"pair_id": "L3_p23", "card_a": {"type": "text", "content": "坚毅"}, "card_b": {"type": "text", "content": "软弱"}},
        {"pair_id": "L3_p24", "card_a": {"type": "text", "content": "博学"}, "card_b": {"type": "text", "content": "无知"}},
        {"pair_id": "L3_p25", "card_a": {"type": "text", "content": "公正"}, "card_b": {"type": "text", "content": "偏颇"}},
        {"pair_id": "L3_p26", "card_a": {"type": "text", "content": "进步"}, "card_b": {"type": "text", "content": "退步"}},
        {"pair_id": "L3_p27", "card_a": {"type": "text", "content": "创新"}, "card_b": {"type": "text", "content": "守旧"}},
        {"pair_id": "L3_p28", "card_a": {"type": "text", "content": "清廉"}, "card_b": {"type": "text", "content": "腐败"}},
        {"pair_id": "L3_p29", "card_a": {"type": "text", "content": "奉献"}, "card_b": {"type": "text", "content": "自私"}},
        {"pair_id": "L3_p30", "card_a": {"type": "text", "content": "包容"}, "card_b": {"type": "text", "content": "排斥"}},
    ],
}


def generate_deck(difficulty: str) -> List[Dict[str, Any]]:
    """
    根据难度生成随机排列的卡片列表。
    从题库中随机抽取10对，每张卡片包含唯一 id、pair_id 和内容信息。
    返回的列表已随机打乱顺序。
    """
    all_pairs = FLIP_CARD_DECKS.get(difficulty, [])
    # 从30对中随机抽取10对
    pairs = list(all_pairs)
    random.shuffle(pairs)
    pairs = pairs[:10]

    cards: List[Dict[str, Any]] = []
    card_index = 1

    for pair in pairs:
        pair_id = pair["pair_id"]
        # 卡片 A
        cards.append({
            "id": f"{difficulty}_card_{card_index:03d}",
            "pair_id": pair_id,
            "type": pair["card_a"]["type"],
            "content": pair["card_a"]["content"],
        })
        card_index += 1
        # 卡片 B
        cards.append({
            "id": f"{difficulty}_card_{card_index:03d}",
            "pair_id": pair_id,
            "type": pair["card_b"]["type"],
            "content": pair["card_b"]["content"],
        })
        card_index += 1

    random.shuffle(cards)
    return cards


# ── 关卡专用题目数据 ──────────────────────────────────────────────────────────

FLIP_CARD_LEVEL_QUESTIONS: dict = {
    "L1": [
        {
            "id": "flip_L1_lv_001",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "山"}, "card_b": {"type": "text", "content": "山"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "水"}, "card_b": {"type": "text", "content": "水"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "日"}, "card_b": {"type": "text", "content": "日"}},
            ],
            "time_limit": 60,
            "preview_duration": 2000,
        },
        {
            "id": "flip_L1_lv_002",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "月"}, "card_b": {"type": "text", "content": "月"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "火"}, "card_b": {"type": "text", "content": "火"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "木"}, "card_b": {"type": "text", "content": "木"}},
            ],
            "time_limit": 60,
            "preview_duration": 1500,
        },
        {
            "id": "flip_L1_lv_003",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "土"}, "card_b": {"type": "text", "content": "土"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "金"}, "card_b": {"type": "text", "content": "金"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "风"}, "card_b": {"type": "text", "content": "风"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "云"}, "card_b": {"type": "text", "content": "云"}},
            ],
            "time_limit": 60,
            "preview_duration": 1500,
        },
        {
            "id": "flip_L1_lv_004",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "花"}, "card_b": {"type": "text", "content": "花"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "草"}, "card_b": {"type": "text", "content": "草"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "鸟"}, "card_b": {"type": "text", "content": "鸟"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "鱼"}, "card_b": {"type": "text", "content": "鱼"}},
            ],
            "time_limit": 60,
            "preview_duration": 1000,
        },
        {
            "id": "flip_L1_lv_005",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "猫"}, "card_b": {"type": "text", "content": "猫"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "狗"}, "card_b": {"type": "text", "content": "狗"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "牛"}, "card_b": {"type": "text", "content": "牛"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "羊"}, "card_b": {"type": "text", "content": "羊"}},
            ],
            "time_limit": 60,
            "preview_duration": 800,
        },
        {
            "id": "flip_L1_lv_006",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "大"}, "card_b": {"type": "text", "content": "大"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "小"}, "card_b": {"type": "text", "content": "小"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "上"}, "card_b": {"type": "text", "content": "上"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "下"}, "card_b": {"type": "text", "content": "下"}},
            ],
            "time_limit": 60,
            "preview_duration": 800,
        },
        {
            "id": "flip_L1_lv_007",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "红"}, "card_b": {"type": "text", "content": "红"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "蓝"}, "card_b": {"type": "text", "content": "蓝"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "绿"}, "card_b": {"type": "text", "content": "绿"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "黄"}, "card_b": {"type": "text", "content": "黄"}},
            ],
            "time_limit": 60,
            "preview_duration": 700,
        },
        {
            "id": "flip_L1_lv_008",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "一"}, "card_b": {"type": "text", "content": "一"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "二"}, "card_b": {"type": "text", "content": "二"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "三"}, "card_b": {"type": "text", "content": "三"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "四"}, "card_b": {"type": "text", "content": "四"}},
            ],
            "time_limit": 60,
            "preview_duration": 700,
        },
        {
            "id": "flip_L1_lv_009",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "春"}, "card_b": {"type": "text", "content": "春"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "夏"}, "card_b": {"type": "text", "content": "夏"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "秋"}, "card_b": {"type": "text", "content": "秋"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "冬"}, "card_b": {"type": "text", "content": "冬"}},
            ],
            "time_limit": 60,
            "preview_duration": 600,
        },
        {
            "id": "flip_L1_lv_010",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "东"}, "card_b": {"type": "text", "content": "东"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "西"}, "card_b": {"type": "text", "content": "西"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "南"}, "card_b": {"type": "text", "content": "南"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "北"}, "card_b": {"type": "text", "content": "北"}},
            ],
            "time_limit": 60,
            "preview_duration": 600,
        },
        {
            "id": "flip_L1_lv_011",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "人"}, "card_b": {"type": "text", "content": "人"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "口"}, "card_b": {"type": "text", "content": "口"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "手"}, "card_b": {"type": "text", "content": "手"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "目"}, "card_b": {"type": "text", "content": "目"}},
            ],
            "time_limit": 60,
            "preview_duration": 600,
        },
        {
            "id": "flip_L1_lv_012",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "书"}, "card_b": {"type": "text", "content": "书"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "笔"}, "card_b": {"type": "text", "content": "笔"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "纸"}, "card_b": {"type": "text", "content": "纸"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "字"}, "card_b": {"type": "text", "content": "字"}},
            ],
            "time_limit": 60,
            "preview_duration": 500,
        },
        {
            "id": "flip_L1_lv_013",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "天"}, "card_b": {"type": "text", "content": "天"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "地"}, "card_b": {"type": "text", "content": "地"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "家"}, "card_b": {"type": "text", "content": "家"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "国"}, "card_b": {"type": "text", "content": "国"}},
            ],
            "time_limit": 60,
            "preview_duration": 500,
        },
        {
            "id": "flip_L1_lv_014",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "爸"}, "card_b": {"type": "text", "content": "爸"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "妈"}, "card_b": {"type": "text", "content": "妈"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "哥"}, "card_b": {"type": "text", "content": "哥"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "姐"}, "card_b": {"type": "text", "content": "姐"}},
            ],
            "time_limit": 60,
            "preview_duration": 500,
        },
        {
            "id": "flip_L1_lv_015",
            "type": "flip_card_match",
            "difficulty": "L1",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到相同的一对",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "好"}, "card_b": {"type": "text", "content": "好"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "多"}, "card_b": {"type": "text", "content": "多"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "快"}, "card_b": {"type": "text", "content": "快"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "乐"}, "card_b": {"type": "text", "content": "乐"}},
            ],
            "time_limit": 60,
            "preview_duration": 400,
        },
    ],
    "L2": [
        {
            "id": "flip_L2_lv_001",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "高兴"}, "card_b": {"type": "text", "content": "快乐"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "漂亮"}, "card_b": {"type": "text", "content": "美丽"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "害怕"}, "card_b": {"type": "text", "content": "恐惧"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "聪明"}, "card_b": {"type": "text", "content": "智慧"}},
            ],
            "time_limit": 75,
            "preview_duration": 1000,
        },
        {
            "id": "flip_L2_lv_002",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "勇敢"}, "card_b": {"type": "text", "content": "胆大"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "悲伤"}, "card_b": {"type": "text", "content": "难过"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "奔跑"}, "card_b": {"type": "text", "content": "飞奔"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "帮助"}, "card_b": {"type": "text", "content": "援助"}},
            ],
            "time_limit": 75,
            "preview_duration": 900,
        },
        {
            "id": "flip_L2_lv_003",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "寻找"}, "card_b": {"type": "text", "content": "寻觅"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "开心"}, "card_b": {"type": "text", "content": "愉快"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "温柔"}, "card_b": {"type": "text", "content": "温和"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "坚强"}, "card_b": {"type": "text", "content": "坚韧"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "思念"}, "card_b": {"type": "text", "content": "想念"}},
            ],
            "time_limit": 90,
            "preview_duration": 800,
        },
        {
            "id": "flip_L2_lv_004",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "宽广"}, "card_b": {"type": "text", "content": "辽阔"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "清晰"}, "card_b": {"type": "text", "content": "清楚"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "珍贵"}, "card_b": {"type": "text", "content": "宝贵"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "迅速"}, "card_b": {"type": "text", "content": "快速"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "安静"}, "card_b": {"type": "text", "content": "宁静"}},
            ],
            "time_limit": 90,
            "preview_duration": 700,
        },
        {
            "id": "flip_L2_lv_005",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "欢喜"}, "card_b": {"type": "text", "content": "喜悦"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "忧愁"}, "card_b": {"type": "text", "content": "忧郁"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "明亮"}, "card_b": {"type": "text", "content": "光亮"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "柔软"}, "card_b": {"type": "text", "content": "柔和"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "强壮"}, "card_b": {"type": "text", "content": "健壮"}},
            ],
            "time_limit": 90,
            "preview_duration": 600,
        },
        {
            "id": "flip_L2_lv_006",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "仔细"}, "card_b": {"type": "text", "content": "认真"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "喜爱"}, "card_b": {"type": "text", "content": "热爱"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "担心"}, "card_b": {"type": "text", "content": "忧虑"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "奇怪"}, "card_b": {"type": "text", "content": "奇特"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "整洁"}, "card_b": {"type": "text", "content": "干净"}},
            ],
            "time_limit": 90,
            "preview_duration": 600,
        },
        {
            "id": "flip_L2_lv_007",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "保护"}, "card_b": {"type": "text", "content": "守护"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "美好"}, "card_b": {"type": "text", "content": "美妙"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "快活"}, "card_b": {"type": "text", "content": "欢乐"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "勤劳"}, "card_b": {"type": "text", "content": "勤奋"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "感谢"}, "card_b": {"type": "text", "content": "感激"}},
            ],
            "time_limit": 90,
            "preview_duration": 500,
        },
        {
            "id": "flip_L2_lv_008",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "温暖"}, "card_b": {"type": "text", "content": "暖和"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "清凉"}, "card_b": {"type": "text", "content": "凉爽"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "广阔"}, "card_b": {"type": "text", "content": "宽阔"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "著名"}, "card_b": {"type": "text", "content": "有名"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "正确"}, "card_b": {"type": "text", "content": "准确"}},
            ],
            "time_limit": 90,
            "preview_duration": 500,
        },
        {
            "id": "flip_L2_lv_009",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "容易"}, "card_b": {"type": "text", "content": "简单"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "困难"}, "card_b": {"type": "text", "content": "艰难"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "期待"}, "card_b": {"type": "text", "content": "盼望"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "惊讶"}, "card_b": {"type": "text", "content": "惊奇"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "平静"}, "card_b": {"type": "text", "content": "平和"}},
            ],
            "time_limit": 90,
            "preview_duration": 500,
        },
        {
            "id": "flip_L2_lv_010",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "聪颖"}, "card_b": {"type": "text", "content": "聪明"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "坚持"}, "card_b": {"type": "text", "content": "坚守"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "丰富"}, "card_b": {"type": "text", "content": "充足"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "疲惫"}, "card_b": {"type": "text", "content": "疲倦"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "聪慧"}, "card_b": {"type": "text", "content": "机智"}},
            ],
            "time_limit": 90,
            "preview_duration": 400,
        },
        {
            "id": "flip_L2_lv_011",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "高大"}, "card_b": {"type": "text", "content": "高耸"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "微小"}, "card_b": {"type": "text", "content": "细小"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "宽敞"}, "card_b": {"type": "text", "content": "宽阔"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "鲜艳"}, "card_b": {"type": "text", "content": "艳丽"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "普通"}, "card_b": {"type": "text", "content": "平常"}},
            ],
            "time_limit": 90,
            "preview_duration": 400,
        },
        {
            "id": "flip_L2_lv_012",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "完整"}, "card_b": {"type": "text", "content": "完全"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "特别"}, "card_b": {"type": "text", "content": "特殊"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "重要"}, "card_b": {"type": "text", "content": "重大"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "简洁"}, "card_b": {"type": "text", "content": "简单"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "善意"}, "card_b": {"type": "text", "content": "好意"}},
            ],
            "time_limit": 90,
            "preview_duration": 400,
        },
        {
            "id": "flip_L2_lv_013",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "忧愁"}, "card_b": {"type": "text", "content": "忧郁"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "奔跑"}, "card_b": {"type": "text", "content": "飞奔"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "帮助"}, "card_b": {"type": "text", "content": "援助"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "寻找"}, "card_b": {"type": "text", "content": "寻觅"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "珍贵"}, "card_b": {"type": "text", "content": "宝贵"}},
            ],
            "time_limit": 90,
            "preview_duration": 400,
        },
        {
            "id": "flip_L2_lv_014",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "迅速"}, "card_b": {"type": "text", "content": "快速"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "安静"}, "card_b": {"type": "text", "content": "宁静"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "清晰"}, "card_b": {"type": "text", "content": "清楚"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "宽广"}, "card_b": {"type": "text", "content": "辽阔"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "思念"}, "card_b": {"type": "text", "content": "想念"}},
            ],
            "time_limit": 90,
            "preview_duration": 400,
        },
        {
            "id": "flip_L2_lv_015",
            "type": "flip_card_match",
            "difficulty": "L2",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到意思相近的词语",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "害怕"}, "card_b": {"type": "text", "content": "恐惧"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "聪明"}, "card_b": {"type": "text", "content": "智慧"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "勇敢"}, "card_b": {"type": "text", "content": "胆大"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "悲伤"}, "card_b": {"type": "text", "content": "难过"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "开心"}, "card_b": {"type": "text", "content": "愉快"}},
            ],
            "time_limit": 90,
            "preview_duration": 400,
        },
    ],
    "L3": [
        {
            "id": "flip_L3_lv_001",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "黑暗"}, "card_b": {"type": "text", "content": "光明"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "寒冷"}, "card_b": {"type": "text", "content": "温暖"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "喜欢"}, "card_b": {"type": "text", "content": "讨厌"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "开始"}, "card_b": {"type": "text", "content": "结束"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "胜利"}, "card_b": {"type": "text", "content": "失败"}},
            ],
            "time_limit": 90,
            "preview_duration": 800,
        },
        {
            "id": "flip_L3_lv_002",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "诚实"}, "card_b": {"type": "text", "content": "虚假"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "努力"}, "card_b": {"type": "text", "content": "懒惰"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "团结"}, "card_b": {"type": "text", "content": "分裂"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "善良"}, "card_b": {"type": "text", "content": "凶恶"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "谦虚"}, "card_b": {"type": "text", "content": "骄傲"}},
            ],
            "time_limit": 90,
            "preview_duration": 700,
        },
        {
            "id": "flip_L3_lv_003",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "宽容"}, "card_b": {"type": "text", "content": "苛刻"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "勤奋"}, "card_b": {"type": "text", "content": "懈怠"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "慷慨"}, "card_b": {"type": "text", "content": "吝啬"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "坚定"}, "card_b": {"type": "text", "content": "动摇"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "乐观"}, "card_b": {"type": "text", "content": "悲观"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "真诚"}, "card_b": {"type": "text", "content": "虚伪"}},
            ],
            "time_limit": 100,
            "preview_duration": 600,
        },
        {
            "id": "flip_L3_lv_004",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "聪慧"}, "card_b": {"type": "text", "content": "愚笨"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "勇猛"}, "card_b": {"type": "text", "content": "懦弱"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "繁荣"}, "card_b": {"type": "text", "content": "衰败"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "清廉"}, "card_b": {"type": "text", "content": "腐败"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "和平"}, "card_b": {"type": "text", "content": "战争"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "自由"}, "card_b": {"type": "text", "content": "束缚"}},
            ],
            "time_limit": 100,
            "preview_duration": 500,
        },
        {
            "id": "flip_L3_lv_005",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "高尚"}, "card_b": {"type": "text", "content": "卑鄙"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "坚毅"}, "card_b": {"type": "text", "content": "软弱"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "博学"}, "card_b": {"type": "text", "content": "无知"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "公正"}, "card_b": {"type": "text", "content": "偏颇"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "进步"}, "card_b": {"type": "text", "content": "退步"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "创新"}, "card_b": {"type": "text", "content": "守旧"}},
            ],
            "time_limit": 100,
            "preview_duration": 400,
        },
        {
            "id": "flip_L3_lv_006",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "清廉"}, "card_b": {"type": "text", "content": "腐败"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "奉献"}, "card_b": {"type": "text", "content": "自私"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "包容"}, "card_b": {"type": "text", "content": "排斥"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "繁荣"}, "card_b": {"type": "text", "content": "衰败"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "和平"}, "card_b": {"type": "text", "content": "战争"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "自由"}, "card_b": {"type": "text", "content": "束缚"}},
            ],
            "time_limit": 100,
            "preview_duration": 400,
        },
        {
            "id": "flip_L3_lv_007",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "黑暗"}, "card_b": {"type": "text", "content": "光明"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "寒冷"}, "card_b": {"type": "text", "content": "温暖"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "喜欢"}, "card_b": {"type": "text", "content": "讨厌"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "开始"}, "card_b": {"type": "text", "content": "结束"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "胜利"}, "card_b": {"type": "text", "content": "失败"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "诚实"}, "card_b": {"type": "text", "content": "虚假"}},
            ],
            "time_limit": 100,
            "preview_duration": 400,
        },
        {
            "id": "flip_L3_lv_008",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "努力"}, "card_b": {"type": "text", "content": "懒惰"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "团结"}, "card_b": {"type": "text", "content": "分裂"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "善良"}, "card_b": {"type": "text", "content": "凶恶"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "谦虚"}, "card_b": {"type": "text", "content": "骄傲"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "宽容"}, "card_b": {"type": "text", "content": "苛刻"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "勤奋"}, "card_b": {"type": "text", "content": "懈怠"}},
            ],
            "time_limit": 100,
            "preview_duration": 400,
        },
        {
            "id": "flip_L3_lv_009",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "慷慨"}, "card_b": {"type": "text", "content": "吝啬"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "坚定"}, "card_b": {"type": "text", "content": "动摇"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "乐观"}, "card_b": {"type": "text", "content": "悲观"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "真诚"}, "card_b": {"type": "text", "content": "虚伪"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "聪慧"}, "card_b": {"type": "text", "content": "愚笨"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "勇猛"}, "card_b": {"type": "text", "content": "懦弱"}},
            ],
            "time_limit": 100,
            "preview_duration": 400,
        },
        {
            "id": "flip_L3_lv_010",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "大"}, "card_b": {"type": "text", "content": "小"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "快"}, "card_b": {"type": "text", "content": "慢"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "冷"}, "card_b": {"type": "text", "content": "热"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "高"}, "card_b": {"type": "text", "content": "低"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "多"}, "card_b": {"type": "text", "content": "少"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "新"}, "card_b": {"type": "text", "content": "旧"}},
            ],
            "time_limit": 100,
            "preview_duration": 400,
        },
        {
            "id": "flip_L3_lv_011",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "来"}, "card_b": {"type": "text", "content": "去"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "开"}, "card_b": {"type": "text", "content": "关"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "买"}, "card_b": {"type": "text", "content": "卖"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "哭"}, "card_b": {"type": "text", "content": "笑"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "爱"}, "card_b": {"type": "text", "content": "恨"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "好"}, "card_b": {"type": "text", "content": "坏"}},
            ],
            "time_limit": 100,
            "preview_duration": 400,
        },
        {
            "id": "flip_L3_lv_012",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "长"}, "card_b": {"type": "text", "content": "短"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "早"}, "card_b": {"type": "text", "content": "晚"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "前"}, "card_b": {"type": "text", "content": "后"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "左"}, "card_b": {"type": "text", "content": "右"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "上"}, "card_b": {"type": "text", "content": "下"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "东"}, "card_b": {"type": "text", "content": "西"}},
            ],
            "time_limit": 100,
            "preview_duration": 400,
        },
        {
            "id": "flip_L3_lv_013",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "问"}, "card_b": {"type": "text", "content": "答"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "胖"}, "card_b": {"type": "text", "content": "瘦"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "深"}, "card_b": {"type": "text", "content": "浅"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "粗"}, "card_b": {"type": "text", "content": "细"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "软"}, "card_b": {"type": "text", "content": "硬"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "轻"}, "card_b": {"type": "text", "content": "重"}},
            ],
            "time_limit": 100,
            "preview_duration": 400,
        },
        {
            "id": "flip_L3_lv_014",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "明"}, "card_b": {"type": "text", "content": "暗"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "干"}, "card_b": {"type": "text", "content": "湿"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "真"}, "card_b": {"type": "text", "content": "假"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "对"}, "card_b": {"type": "text", "content": "错"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "美"}, "card_b": {"type": "text", "content": "丑"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "甜"}, "card_b": {"type": "text", "content": "苦"}},
            ],
            "time_limit": 100,
            "preview_duration": 400,
        },
        {
            "id": "flip_L3_lv_015",
            "type": "flip_card_match",
            "difficulty": "L3",
            "title": "翻牌配对",
            "instruction": "翻开卡片，找到反义词",
            "pairs": [
                {"pair_id": "p1", "card_a": {"type": "text", "content": "胜"}, "card_b": {"type": "text", "content": "败"}},
                {"pair_id": "p2", "card_a": {"type": "text", "content": "生"}, "card_b": {"type": "text", "content": "死"}},
                {"pair_id": "p3", "card_a": {"type": "text", "content": "进"}, "card_b": {"type": "text", "content": "退"}},
                {"pair_id": "p4", "card_a": {"type": "text", "content": "升"}, "card_b": {"type": "text", "content": "降"}},
                {"pair_id": "p5", "card_a": {"type": "text", "content": "增"}, "card_b": {"type": "text", "content": "减"}},
                {"pair_id": "p6", "card_a": {"type": "text", "content": "收"}, "card_b": {"type": "text", "content": "放"}},
            ],
            "time_limit": 100,
            "preview_duration": 400,
        },
    ],
}

# ── 关卡数据 ──────────────────────────────────────────────────────────────────

FLIP_CARD_GAME_LEVELS: dict = {
    "L1": [
        {
            "level_id": "flip_card_L1_lv1",
            "level_num": 1,
            "title": "第1关",
            "difficulty": "L1",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L1"][0]],
        },
        {
            "level_id": "flip_card_L1_lv2",
            "level_num": 2,
            "title": "第2关",
            "difficulty": "L1",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L1"][1]],
        },
        {
            "level_id": "flip_card_L1_lv3",
            "level_num": 3,
            "title": "第3关",
            "difficulty": "L1",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L1"][2]],
        },
        {
            "level_id": "flip_card_L1_lv4",
            "level_num": 4,
            "title": "第4关",
            "difficulty": "L1",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L1"][3]],
        },
        {
            "level_id": "flip_card_L1_lv5",
            "level_num": 5,
            "title": "第5关",
            "difficulty": "L1",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L1"][4]],
        },
    ],
    "L2": [
        {
            "level_id": "flip_card_L2_lv1",
            "level_num": 1,
            "title": "第1关",
            "difficulty": "L2",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L2"][0]],
        },
        {
            "level_id": "flip_card_L2_lv2",
            "level_num": 2,
            "title": "第2关",
            "difficulty": "L2",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L2"][1]],
        },
        {
            "level_id": "flip_card_L2_lv3",
            "level_num": 3,
            "title": "第3关",
            "difficulty": "L2",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L2"][2]],
        },
        {
            "level_id": "flip_card_L2_lv4",
            "level_num": 4,
            "title": "第4关",
            "difficulty": "L2",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L2"][3]],
        },
        {
            "level_id": "flip_card_L2_lv5",
            "level_num": 5,
            "title": "第5关",
            "difficulty": "L2",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L2"][4]],
        },
    ],
    "L3": [
        {
            "level_id": "flip_card_L3_lv1",
            "level_num": 1,
            "title": "第1关",
            "difficulty": "L3",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L3"][0]],
        },
        {
            "level_id": "flip_card_L3_lv2",
            "level_num": 2,
            "title": "第2关",
            "difficulty": "L3",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L3"][1]],
        },
        {
            "level_id": "flip_card_L3_lv3",
            "level_num": 3,
            "title": "第3关",
            "difficulty": "L3",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L3"][2]],
        },
        {
            "level_id": "flip_card_L3_lv4",
            "level_num": 4,
            "title": "第4关",
            "difficulty": "L3",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L3"][3]],
        },
        {
            "level_id": "flip_card_L3_lv5",
            "level_num": 5,
            "title": "第5关",
            "difficulty": "L3",
            "game_type": "flip_card",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["flip_card_match"],
            "questions": [FLIP_CARD_LEVEL_QUESTIONS["L3"][4]],
        },
    ],
}
