"""
手写汉字游戏题库
难度分级：
  L1 — 3-5 画基础汉字
  L2 — 6-9 画常用汉字
  L3 — 10 画及以上汉字
"""
import random
from typing import List, Dict, Any, Optional

HANDWRITING_QUESTIONS: Dict[str, List[Dict[str, Any]]] = {
    "L1": [
        # 1-5画基础汉字 —— 共30题，每次随机抽10题
        {
            "id": "hw_L1_001",
            "character": "一",
            "stroke_count": 1,
            "stroke_order": ["横"],
            "stroke_paths": [],
            "difficulty": "L1",
            "time_limit": 30,
        },
        {
            "id": "hw_L1_002",
            "character": "二",
            "stroke_count": 2,
            "stroke_order": ["横", "横"],
            "stroke_paths": [],
            "difficulty": "L1",
            "time_limit": 30,
        },
        {
            "id": "hw_L1_003",
            "character": "三",
            "stroke_count": 3,
            "stroke_order": ["横", "横", "横"],
            "stroke_paths": [],
            "difficulty": "L1",
            "time_limit": 30,
        },
        {
            "id": "hw_L1_004",
            "character": "人",
            "stroke_count": 2,
            "stroke_order": ["撇", "捺"],
            "stroke_paths": [],
            "difficulty": "L1",
            "time_limit": 30,
        },
        {
            "id": "hw_L1_005",
            "character": "口",
            "stroke_count": 3,
            "stroke_order": ["竖", "横折", "横"],
            "stroke_paths": [],
            "difficulty": "L1",
            "time_limit": 30,
        },
        {"id": "hw_L1_006", "character": "山", "stroke_count": 3, "stroke_order": ["竖", "竖折", "竖"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_007", "character": "大", "stroke_count": 3, "stroke_order": ["横", "撇", "捺"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_008", "character": "小", "stroke_count": 3, "stroke_order": ["竖钩", "点", "点"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_009", "character": "上", "stroke_count": 3, "stroke_order": ["竖", "横", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_010", "character": "下", "stroke_count": 3, "stroke_order": ["横", "竖", "点"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_011", "character": "土", "stroke_count": 3, "stroke_order": ["横", "竖", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_012", "character": "工", "stroke_count": 3, "stroke_order": ["横", "竖", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_013", "character": "日", "stroke_count": 4, "stroke_order": ["竖", "横折", "横", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_014", "character": "月", "stroke_count": 4, "stroke_order": ["撇", "横折钩", "横", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_015", "character": "木", "stroke_count": 4, "stroke_order": ["横", "竖", "撇", "捺"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_016", "character": "水", "stroke_count": 4, "stroke_order": ["横撇", "竖钩", "撇", "捺"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_017", "character": "火", "stroke_count": 4, "stroke_order": ["点", "撇", "撇", "捺"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_018", "character": "王", "stroke_count": 4, "stroke_order": ["横", "横", "竖", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_019", "character": "天", "stroke_count": 4, "stroke_order": ["横", "横", "撇", "捺"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_020", "character": "中", "stroke_count": 4, "stroke_order": ["竖", "横折", "横", "竖"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_021", "character": "心", "stroke_count": 4, "stroke_order": ["点", "卧钩", "点", "点"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_022", "character": "手", "stroke_count": 4, "stroke_order": ["横", "横", "横", "弯钩"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_023", "character": "目", "stroke_count": 5, "stroke_order": ["竖", "横折", "横", "横", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_024", "character": "田", "stroke_count": 5, "stroke_order": ["竖", "横折", "横", "竖", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_025", "character": "白", "stroke_count": 5, "stroke_order": ["撇", "横折", "横", "横", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_026", "character": "石", "stroke_count": 5, "stroke_order": ["横", "撇", "竖", "横折", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_027", "character": "立", "stroke_count": 5, "stroke_order": ["点", "横", "撇", "捺", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_028", "character": "本", "stroke_count": 5, "stroke_order": ["横", "竖", "撇", "捺", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_029", "character": "正", "stroke_count": 5, "stroke_order": ["横", "竖", "横", "竖", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
        {"id": "hw_L1_030", "character": "生", "stroke_count": 5, "stroke_order": ["撇", "横", "竖", "横", "横"], "stroke_paths": [], "difficulty": "L1", "time_limit": 30},
    ],
    "L2": [
        # 5-9画常用汉字 —— 共30题，每次随机抽10题
        {
            "id": "hw_L2_001",
            "character": "你",
            "stroke_count": 7,
            "stroke_order": ["撇", "竖", "撇", "横", "竖钩", "撇", "点"],
            "stroke_paths": [],
            "difficulty": "L2",
            "time_limit": 45,
        },
        {
            "id": "hw_L2_002",
            "character": "我",
            "stroke_count": 7,
            "stroke_order": ["横", "竖钩", "撇", "横", "斜钩", "撇", "点"],
            "stroke_paths": [],
            "difficulty": "L2",
            "time_limit": 45,
        },
        {
            "id": "hw_L2_003",
            "character": "他",
            "stroke_count": 5,
            "stroke_order": ["撇", "竖", "横", "竖", "横折钩"],
            "stroke_paths": [],
            "difficulty": "L2",
            "time_limit": 45,
        },
        {
            "id": "hw_L2_004",
            "character": "好",
            "stroke_count": 6,
            "stroke_order": ["撇折", "点", "横折", "横", "竖", "横"],
            "stroke_paths": [],
            "difficulty": "L2",
            "time_limit": 45,
        },
        {
            "id": "hw_L2_005",
            "character": "学",
            "stroke_count": 8,
            "stroke_order": ["点", "点", "横撇", "点", "横折", "横", "竖", "横"],
            "stroke_paths": [],
            "difficulty": "L2",
            "time_limit": 45,
        },
        {"id": "hw_L2_006", "character": "天", "stroke_count": 4, "stroke_order": ["横", "横", "撇", "捺"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_007", "character": "地", "stroke_count": 6, "stroke_order": ["横", "竖", "横折钩", "横", "撇", "竖弯钩"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_008", "character": "来", "stroke_count": 7, "stroke_order": ["横", "撇", "捺", "竖", "撇", "点", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_009", "character": "去", "stroke_count": 5, "stroke_order": ["横", "竖折", "横", "撇", "捺"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_010", "character": "看", "stroke_count": 9, "stroke_order": ["横", "撇", "竖", "横", "横", "竖", "横折", "横", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_011", "character": "走", "stroke_count": 7, "stroke_order": ["横", "竖", "横", "撇", "捺", "横", "竖弯钩"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_012", "character": "吃", "stroke_count": 6, "stroke_order": ["竖", "横折", "横", "撇", "横折钩", "撇"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_013", "character": "玩", "stroke_count": 8, "stroke_order": ["横", "竖", "横折", "横", "横", "撇", "横折钩", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_014", "character": "花", "stroke_count": 7, "stroke_order": ["横", "竖", "撇", "横折钩", "横", "撇", "捺"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_015", "character": "草", "stroke_count": 9, "stroke_order": ["横", "竖", "横", "竖", "横", "横", "竖", "横折", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_016", "character": "鸟", "stroke_count": 5, "stroke_order": ["撇折", "点", "横折钩", "横", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_017", "character": "鱼", "stroke_count": 8, "stroke_order": ["撇", "横折", "横", "横", "横", "竖", "横折", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_018", "character": "红", "stroke_count": 6, "stroke_order": ["横", "竖钩", "提", "横折", "横", "竖弯钩"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_019", "character": "画", "stroke_count": 8, "stroke_order": ["横", "竖", "横折", "横", "横", "竖", "横折", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_020", "character": "明", "stroke_count": 8, "stroke_order": ["撇", "横折钩", "横", "横", "竖", "横折", "横", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_021", "character": "问", "stroke_count": 6, "stroke_order": ["点", "横折钩", "横", "竖", "横折", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_022", "character": "笑", "stroke_count": 10, "stroke_order": ["横", "竖", "横", "撇", "横折", "横", "横", "撇", "横折", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_023", "character": "快", "stroke_count": 7, "stroke_order": ["点", "横折提", "横", "竖", "横折", "横", "捺"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_024", "character": "乐", "stroke_count": 5, "stroke_order": ["横", "竖", "撇", "横折钩", "捺"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_025", "character": "美", "stroke_count": 9, "stroke_order": ["横", "横", "竖", "撇", "捺", "横", "竖", "撇", "捺"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_026", "character": "真", "stroke_count": 10, "stroke_order": ["横", "竖", "横折", "横", "横", "横", "竖", "横折", "横", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_027", "character": "树", "stroke_count": 9, "stroke_order": ["横", "竖", "撇", "捺", "横", "竖", "横折", "横", "撇"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_028", "character": "狗", "stroke_count": 8, "stroke_order": ["撇", "竖", "横折钩", "横", "横", "撇", "横折钩", "撇"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_029", "character": "猫", "stroke_count": 11, "stroke_order": ["撇", "竖", "横折钩", "横", "横", "竖", "横折", "横", "横", "竖", "横折"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
        {"id": "hw_L2_030", "character": "国", "stroke_count": 8, "stroke_order": ["竖", "横折", "横", "竖", "横折", "横", "横", "横"], "stroke_paths": [], "difficulty": "L2", "time_limit": 45},
    ],
    "L3": [
        # 8画及以上汉字 —— 共30题，每次随机抽10题
        {
            "id": "hw_L3_001",
            "character": "爱",
            "stroke_count": 10,
            "stroke_order": ["横折", "点", "撇", "横", "竖", "横", "撇", "捺", "撇", "点"],
            "stroke_paths": [],
            "difficulty": "L3",
            "time_limit": 60,
        },
        {
            "id": "hw_L3_002",
            "character": "家",
            "stroke_count": 10,
            "stroke_order": ["点", "横撇", "竖", "横折", "横", "撇", "竖弯钩", "撇", "撇", "捺"],
            "stroke_paths": [],
            "difficulty": "L3",
            "time_limit": 60,
        },
        {
            "id": "hw_L3_003",
            "character": "朋",
            "stroke_count": 8,
            "stroke_order": ["横折钩", "横", "横", "竖", "横折钩", "横", "横", "竖"],
            "stroke_paths": [],
            "difficulty": "L3",
            "time_limit": 60,
        },
        {
            "id": "hw_L3_004",
            "character": "友",
            "stroke_count": 4,
            "stroke_order": ["横", "撇", "撇", "捺"],
            "stroke_paths": [],
            "difficulty": "L3",
            "time_limit": 60,
        },
        {
            "id": "hw_L3_005",
            "character": "读",
            "stroke_count": 10,
            "stroke_order": ["点", "横折提", "点", "撇", "横", "竖", "横折", "横", "撇", "点"],
            "stroke_paths": [],
            "difficulty": "L3",
            "time_limit": 60,
        },
        {"id": "hw_L3_006", "character": "写", "stroke_count": 5, "stroke_order": ["横折", "横", "撇", "竖折", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_007", "character": "书", "stroke_count": 4, "stroke_order": ["横折", "横折钩", "竖", "点"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_008", "character": "语", "stroke_count": 9, "stroke_order": ["点", "横折提", "点", "横折", "横", "竖", "横折", "横", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_009", "character": "数", "stroke_count": 13, "stroke_order": ["横", "竖", "撇", "横折", "横", "横", "竖", "横折", "横", "撇", "横折钩", "撇", "捺"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_010", "character": "校", "stroke_count": 10, "stroke_order": ["横", "竖", "撇", "捺", "横", "竖", "撇", "横折钩", "撇", "捺"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_011", "character": "国", "stroke_count": 8, "stroke_order": ["竖", "横折", "横", "竖", "横折", "横", "横", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_012", "character": "想", "stroke_count": 13, "stroke_order": ["横", "竖", "横折", "横", "横", "竖", "横折", "横", "横", "点", "卧钩", "点", "点"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_013", "character": "感", "stroke_count": 13, "stroke_order": ["横", "竖", "横折", "横", "横", "竖", "横折", "横", "撇", "横折钩", "横", "点", "点"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_014", "character": "情", "stroke_count": 11, "stroke_order": ["点", "横折提", "点", "横折", "横", "竖", "横折", "横", "横", "竖", "横折"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_015", "character": "游", "stroke_count": 12, "stroke_order": ["点", "横折提", "点", "横折", "横", "竖", "横折", "横", "横", "撇", "横折钩", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_016", "character": "唱", "stroke_count": 11, "stroke_order": ["竖", "横折", "横", "横", "竖", "横折", "横", "横", "竖", "横折", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_017", "character": "跳", "stroke_count": 13, "stroke_order": ["竖", "横折", "横", "横", "竖", "横", "撇", "横折钩", "横", "横", "撇", "横折", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_018", "character": "跑", "stroke_count": 12, "stroke_order": ["竖", "横折", "横", "横", "竖", "横", "撇", "横折钩", "横", "横", "撇", "捺"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_019", "character": "笑", "stroke_count": 10, "stroke_order": ["横", "竖", "横", "撇", "横折", "横", "横", "撇", "横折", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_020", "character": "哭", "stroke_count": 10, "stroke_order": ["竖", "横折", "横", "竖", "横折", "横", "横", "撇", "横折钩", "撇"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_021", "character": "勇", "stroke_count": 9, "stroke_order": ["横折", "横", "竖", "横折", "横", "横", "竖", "横折钩", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_022", "character": "智", "stroke_count": 12, "stroke_order": ["横", "竖", "横折", "横", "横", "竖", "横折", "横", "横", "竖", "横折", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_023", "character": "美", "stroke_count": 9, "stroke_order": ["横", "横", "竖", "撇", "捺", "横", "竖", "撇", "捺"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_024", "character": "真", "stroke_count": 10, "stroke_order": ["横", "竖", "横折", "横", "横", "横", "竖", "横折", "横", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_025", "character": "答", "stroke_count": 12, "stroke_order": ["撇", "横折", "横", "横", "竖", "横折", "横", "横", "竖", "横折", "横", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_026", "character": "问", "stroke_count": 6, "stroke_order": ["点", "横折钩", "横", "竖", "横折", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_027", "character": "明", "stroke_count": 8, "stroke_order": ["撇", "横折钩", "横", "横", "竖", "横折", "横", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_028", "character": "画", "stroke_count": 8, "stroke_order": ["横", "竖", "横折", "横", "横", "竖", "横折", "横"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_029", "character": "快", "stroke_count": 7, "stroke_order": ["点", "横折提", "横", "竖", "横折", "横", "捺"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
        {"id": "hw_L3_030", "character": "乐", "stroke_count": 5, "stroke_order": ["横", "竖", "撇", "横折钩", "捺"], "stroke_paths": [], "difficulty": "L3", "time_limit": 60},
    ],
}


def get_questions(difficulty: str) -> List[Dict[str, Any]]:
    """返回指定难度的全部题目列表。"""
    return HANDWRITING_QUESTIONS.get(difficulty, [])


def get_random_question(difficulty: str) -> Optional[Dict[str, Any]]:
    """随机返回指定难度的一道题目；若难度不存在则返回 None。"""
    questions = get_questions(difficulty)
    if not questions:
        return None
    return random.choice(questions)


# ── 关卡专用题目数据 ──────────────────────────────────────────────────────────

HANDWRITING_LEVEL_QUESTIONS: dict = {
    "L1": [
        {
            "id": "hw_lv_L1_001",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "一",
            "stroke_count": 1,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_002",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "二",
            "stroke_count": 2,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_003",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "三",
            "stroke_count": 3,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_004",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "人",
            "stroke_count": 2,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_005",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "口",
            "stroke_count": 3,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_006",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "山",
            "stroke_count": 3,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_007",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "大",
            "stroke_count": 3,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_008",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "小",
            "stroke_count": 3,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_009",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "上",
            "stroke_count": 3,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_010",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "下",
            "stroke_count": 3,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_011",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "土",
            "stroke_count": 3,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_012",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "日",
            "stroke_count": 4,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_013",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "月",
            "stroke_count": 4,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_014",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "木",
            "stroke_count": 4,
            "time_limit": 30,
        },
        {
            "id": "hw_lv_L1_015",
            "type": "handwriting_trace",
            "difficulty": "L1",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "水",
            "stroke_count": 4,
            "time_limit": 30,
        },
    ],
    "L2": [
        {
            "id": "hw_lv_L2_001",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "你",
            "stroke_count": 7,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_002",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "我",
            "stroke_count": 7,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_003",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "他",
            "stroke_count": 5,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_004",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "好",
            "stroke_count": 6,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_005",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "学",
            "stroke_count": 8,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_006",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "天",
            "stroke_count": 4,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_007",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "地",
            "stroke_count": 6,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_008",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "来",
            "stroke_count": 7,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_009",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "去",
            "stroke_count": 5,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_010",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "看",
            "stroke_count": 9,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_011",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "走",
            "stroke_count": 7,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_012",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "吃",
            "stroke_count": 6,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_013",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "花",
            "stroke_count": 7,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_014",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "红",
            "stroke_count": 6,
            "time_limit": 25,
        },
        {
            "id": "hw_lv_L2_015",
            "type": "handwriting_trace",
            "difficulty": "L2",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "明",
            "stroke_count": 8,
            "time_limit": 25,
        },
    ],
    "L3": [
        {
            "id": "hw_lv_L3_001",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "爱",
            "stroke_count": 10,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_002",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "家",
            "stroke_count": 10,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_003",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "朋",
            "stroke_count": 8,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_004",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "读",
            "stroke_count": 10,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_005",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "写",
            "stroke_count": 5,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_006",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "书",
            "stroke_count": 4,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_007",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "语",
            "stroke_count": 9,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_008",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "数",
            "stroke_count": 13,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_009",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "学",
            "stroke_count": 8,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_010",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "校",
            "stroke_count": 10,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_011",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "想",
            "stroke_count": 13,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_012",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "感",
            "stroke_count": 13,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_013",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "游",
            "stroke_count": 12,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_014",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "跳",
            "stroke_count": 13,
            "time_limit": 20,
        },
        {
            "id": "hw_lv_L3_015",
            "type": "handwriting_trace",
            "difficulty": "L3",
            "title": "写一写",
            "instruction": "按照笔顺描摹这个字",
            "character": "唱",
            "stroke_count": 11,
            "time_limit": 20,
        },
    ],
}

# ── 关卡数据 ──────────────────────────────────────────────────────────────────

HANDWRITING_GAME_LEVELS: dict = {
    "L1": [
        {
            "level_id": "handwriting_L1_lv1",
            "level_num": 1,
            "title": "第1关",
            "difficulty": "L1",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L1"][0:2],
        },
        {
            "level_id": "handwriting_L1_lv2",
            "level_num": 2,
            "title": "第2关",
            "difficulty": "L1",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L1"][2:4],
        },
        {
            "level_id": "handwriting_L1_lv3",
            "level_num": 3,
            "title": "第3关",
            "difficulty": "L1",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L1"][4:7],
        },
        {
            "level_id": "handwriting_L1_lv4",
            "level_num": 4,
            "title": "第4关",
            "difficulty": "L1",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L1"][7:9],
        },
        {
            "level_id": "handwriting_L1_lv5",
            "level_num": 5,
            "title": "第5关",
            "difficulty": "L1",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L1"][7:10],
        },
    ],
    "L2": [
        {
            "level_id": "handwriting_L2_lv1",
            "level_num": 1,
            "title": "第1关",
            "difficulty": "L2",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L2"][0:2],
        },
        {
            "level_id": "handwriting_L2_lv2",
            "level_num": 2,
            "title": "第2关",
            "difficulty": "L2",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L2"][2:4],
        },
        {
            "level_id": "handwriting_L2_lv3",
            "level_num": 3,
            "title": "第3关",
            "difficulty": "L2",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L2"][4:7],
        },
        {
            "level_id": "handwriting_L2_lv4",
            "level_num": 4,
            "title": "第4关",
            "difficulty": "L2",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L2"][7:9],
        },
        {
            "level_id": "handwriting_L2_lv5",
            "level_num": 5,
            "title": "第5关",
            "difficulty": "L2",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L2"][7:10],
        },
    ],
    "L3": [
        {
            "level_id": "handwriting_L3_lv1",
            "level_num": 1,
            "title": "第1关",
            "difficulty": "L3",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L3"][0:2],
        },
        {
            "level_id": "handwriting_L3_lv2",
            "level_num": 2,
            "title": "第2关",
            "difficulty": "L3",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L3"][2:4],
        },
        {
            "level_id": "handwriting_L3_lv3",
            "level_num": 3,
            "title": "第3关",
            "difficulty": "L3",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L3"][4:7],
        },
        {
            "level_id": "handwriting_L3_lv4",
            "level_num": 4,
            "title": "第4关",
            "difficulty": "L3",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L3"][7:9],
        },
        {
            "level_id": "handwriting_L3_lv5",
            "level_num": 5,
            "title": "第5关",
            "difficulty": "L3",
            "game_type": "handwriting",
            "pass_condition": {"min_accuracy": 0.7},
            "question_types": ["handwriting_trace"],
            "questions": HANDWRITING_LEVEL_QUESTIONS["L3"][7:10],
        },
    ],
}
